"""add_rule_prompts_table

Revision ID: 18a3071f0e76
Revises: p4e7f6g5h852
Create Date: 2026-06-05 10:00:50.608363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '18a3071f0e76'
down_revision: Union[str, None] = 'p4e7f6g5h852'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule_prompts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('output_schema', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('model', sa.String(length=80), server_default='claude-sonnet-4-6', nullable=False),
    sa.Column('temperature', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('last_edited_by', sa.String(length=100), nullable=True),
    sa.Column('last_edited_at', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('eval_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule_prompts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_prompts_rule_id'), ['rule_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_prompts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_prompts_rule_id'))

    op.drop_table('rule_prompts')
    # ### end Alembic commands ###
