"""initial_schema

Revision ID: 20bc1e724080
Revises: 
Create Date: 2026-05-05 14:58:42.976290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20bc1e724080'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_headers_837',
    sa.Column('header_id', sa.String(length=36), nullable=False),
    sa.Column('claim_icn', sa.String(length=100), nullable=False),
    sa.Column('submitter_npi', sa.String(length=20), nullable=False),
    sa.Column('billing_provider_npi', sa.String(length=20), nullable=False),
    sa.Column('submission_date', sa.String(length=10), nullable=False),
    sa.Column('total_billed', sa.Float(), nullable=False),
    sa.Column('claim_frequency_code', sa.String(length=5), nullable=False),
    sa.Column('raw_837_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('header_id'),
    sa.UniqueConstraint('claim_icn')
    )
    op.create_table('cpt_codes',
    sa.Column('cpt_code_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('value_tier', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('typical_units_max', sa.Integer(), nullable=False),
    sa.Column('requires_auth', sa.Boolean(), nullable=False),
    sa.Column('specialty_typical', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('cpt_code_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('cpt_icd_risks',
    sa.Column('cpt_icd_risk_id', sa.String(length=36), nullable=False),
    sa.Column('cpt_code', sa.String(length=10), nullable=False),
    sa.Column('icd_code', sa.String(length=10), nullable=False),
    sa.Column('mismatch_risk_score', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('cpt_icd_risk_id')
    )
    op.create_table('icd_codes',
    sa.Column('icd_code_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('value_tier', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('icd_code_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('members',
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('member_number', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.String(length=10), nullable=False),
    sa.Column('date_of_death', sa.String(length=10), nullable=True),
    sa.Column('lob', sa.String(length=50), nullable=False),
    sa.Column('coverage_effective_date', sa.String(length=10), nullable=False),
    sa.Column('coverage_termination_date', sa.String(length=10), nullable=True),
    sa.Column('retro_termination_date', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('member_id'),
    sa.UniqueConstraint('member_number')
    )
    op.create_table('ml_model_versions',
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_artifact_id', sa.String(length=255), nullable=False),
    sa.Column('trained_at', sa.String(length=30), nullable=False),
    sa.Column('training_rows', sa.Integer(), nullable=False),
    sa.Column('training_window', sa.String(length=50), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('positive_rate', sa.Float(), nullable=False),
    sa.Column('feature_importance', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_table('opa_users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('provider_orgs',
    sa.Column('provider_org_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('npi', sa.String(length=20), nullable=False),
    sa.Column('tin', sa.String(length=20), nullable=False),
    sa.Column('org_type', sa.String(length=50), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('provider_org_id'),
    sa.UniqueConstraint('npi')
    )
    op.create_table('reference_data_freshness',
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('last_refreshed_at', sa.String(length=30), nullable=False),
    sa.Column('next_scheduled_refresh', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('affected_detectors', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('source_name')
    )
    op.create_table('case_groups',
    sa.Column('case_group_id', sa.String(length=36), nullable=False),
    sa.Column('group_number', sa.String(length=50), nullable=False),
    sa.Column('provider_org_id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('dos_range_start', sa.String(length=10), nullable=False),
    sa.Column('dos_range_end', sa.String(length=10), nullable=False),
    sa.Column('group_reason', sa.Text(), nullable=False),
    sa.Column('duplicate_suspected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ),
    sa.ForeignKeyConstraint(['provider_org_id'], ['provider_orgs.provider_org_id'], ),
    sa.PrimaryKeyConstraint('case_group_id'),
    sa.UniqueConstraint('group_number')
    )
    op.create_table('contract_limitations',
    sa.Column('limitation_id', sa.String(length=36), nullable=False),
    sa.Column('provider_org_id', sa.String(length=36), nullable=False),
    sa.Column('cpt_code', sa.String(length=10), nullable=False),
    sa.Column('limitation_type', sa.String(length=50), nullable=False),
    sa.Column('limitation_value', sa.String(length=100), nullable=False),
    sa.Column('effective_date', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['provider_org_id'], ['provider_orgs.provider_org_id'], ),
    sa.PrimaryKeyConstraint('limitation_id')
    )
    op.create_table('fee_schedules',
    sa.Column('fee_schedule_id', sa.String(length=36), nullable=False),
    sa.Column('provider_org_id', sa.String(length=36), nullable=False),
    sa.Column('lob', sa.String(length=50), nullable=False),
    sa.Column('cpt_code', sa.String(length=10), nullable=False),
    sa.Column('effective_date', sa.String(length=10), nullable=False),
    sa.Column('termination_date', sa.String(length=10), nullable=True),
    sa.Column('base_rate', sa.Float(), nullable=False),
    sa.Column('rate_basis', sa.String(length=50), nullable=False),
    sa.Column('modifier_applicable', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['provider_org_id'], ['provider_orgs.provider_org_id'], ),
    sa.PrimaryKeyConstraint('fee_schedule_id')
    )
    op.create_table('letter_templates',
    sa.Column('template_id', sa.String(length=100), nullable=False),
    sa.Column('lob', sa.String(length=50), nullable=False),
    sa.Column('template_name', sa.String(length=255), nullable=False),
    sa.Column('regulatory_reference', sa.Text(), nullable=False),
    sa.Column('template_content', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['opa_users.user_id'], ),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_table('providers',
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('provider_org_id', sa.String(length=36), nullable=False),
    sa.Column('npi', sa.String(length=20), nullable=False),
    sa.Column('tin', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('credential_status', sa.String(length=50), nullable=False),
    sa.Column('credential_effective_date', sa.String(length=10), nullable=False),
    sa.Column('credential_lapse_date', sa.String(length=10), nullable=True),
    sa.Column('is_excluded', sa.Boolean(), nullable=False),
    sa.Column('exclusion_effective_date', sa.String(length=10), nullable=True),
    sa.Column('exclusion_source', sa.String(length=100), nullable=True),
    sa.Column('billing_variance_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['provider_org_id'], ['provider_orgs.provider_org_id'], ),
    sa.PrimaryKeyConstraint('provider_id'),
    sa.UniqueConstraint('npi')
    )
    op.create_table('transactions_835',
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_number', sa.String(length=100), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('payer_name', sa.String(length=255), nullable=False),
    sa.Column('provider_org_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_date', sa.String(length=10), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('claim_count', sa.Integer(), nullable=False),
    sa.Column('raw_835_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['provider_org_id'], ['provider_orgs.provider_org_id'], ),
    sa.PrimaryKeyConstraint('transaction_id'),
    sa.UniqueConstraint('transaction_number')
    )
    op.create_table('claim_payments_835',
    sa.Column('payment_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('claim_icn', sa.String(length=100), nullable=False),
    sa.Column('cpt_code', sa.String(length=10), nullable=False),
    sa.Column('paid_amount', sa.Float(), nullable=False),
    sa.Column('adjustment_amount', sa.Float(), nullable=False),
    sa.Column('adjustment_reason_code', sa.String(length=20), nullable=True),
    sa.Column('check_number', sa.String(length=50), nullable=True),
    sa.Column('payment_date', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions_835.transaction_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_table('claims',
    sa.Column('claim_id', sa.String(length=36), nullable=False),
    sa.Column('icn', sa.String(length=100), nullable=False),
    sa.Column('case_group_id', sa.String(length=36), nullable=True),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('provider_org_id', sa.String(length=36), nullable=False),
    sa.Column('billing_provider_npi', sa.String(length=20), nullable=False),
    sa.Column('rendering_provider_npi', sa.String(length=20), nullable=False),
    sa.Column('lob', sa.String(length=50), nullable=False),
    sa.Column('service_from_date', sa.String(length=10), nullable=False),
    sa.Column('service_to_date', sa.String(length=10), nullable=False),
    sa.Column('claim_type', sa.String(length=50), nullable=False),
    sa.Column('claim_status', sa.String(length=50), nullable=False),
    sa.Column('total_billed', sa.Float(), nullable=False),
    sa.Column('total_paid', sa.Float(), nullable=False),
    sa.Column('paid_date', sa.String(length=10), nullable=False),
    sa.Column('authorization_number', sa.String(length=50), nullable=True),
    sa.Column('submission_date', sa.String(length=10), nullable=False),
    sa.Column('pos_code', sa.String(length=5), nullable=False),
    sa.Column('primary_icd', sa.String(length=10), nullable=False),
    sa.Column('era_transaction_id', sa.String(length=36), nullable=True),
    sa.Column('raw_claim_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['case_group_id'], ['case_groups.case_group_id'], ),
    sa.ForeignKeyConstraint(['era_transaction_id'], ['transactions_835.transaction_id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ),
    sa.ForeignKeyConstraint(['provider_org_id'], ['provider_orgs.provider_org_id'], ),
    sa.PrimaryKeyConstraint('claim_id'),
    sa.UniqueConstraint('icn')
    )
    op.create_table('claim_lines',
    sa.Column('claim_line_id', sa.String(length=36), nullable=False),
    sa.Column('claim_id', sa.String(length=36), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('cpt_code', sa.String(length=10), nullable=False),
    sa.Column('icd_codes', sa.Text(), nullable=False),
    sa.Column('modifier_1', sa.String(length=5), nullable=True),
    sa.Column('modifier_2', sa.String(length=5), nullable=True),
    sa.Column('units_billed', sa.Integer(), nullable=False),
    sa.Column('units_paid', sa.Integer(), nullable=False),
    sa.Column('billed_amount', sa.Float(), nullable=False),
    sa.Column('paid_amount', sa.Float(), nullable=False),
    sa.Column('allowed_amount', sa.Float(), nullable=False),
    sa.Column('pos_code', sa.String(length=5), nullable=False),
    sa.Column('revenue_code', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.claim_id'], ),
    sa.PrimaryKeyConstraint('claim_line_id')
    )
    op.create_table('opa_cases',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('case_number', sa.String(length=50), nullable=False),
    sa.Column('case_sequence', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.String(length=36), nullable=False),
    sa.Column('case_group_id', sa.String(length=36), nullable=True),
    sa.Column('primary_detector_id', sa.String(length=50), nullable=False),
    sa.Column('lob', sa.String(length=50), nullable=False),
    sa.Column('provider_org_id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_analyst_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('total_overpayment_amount', sa.Float(), nullable=False),
    sa.Column('recommended_recovery_method', sa.String(length=50), nullable=False),
    sa.Column('identified_date', sa.String(length=10), nullable=False),
    sa.Column('deadline_date', sa.String(length=10), nullable=False),
    sa.Column('deadline_breached', sa.Boolean(), nullable=False),
    sa.Column('lookback_window_start', sa.String(length=10), nullable=False),
    sa.Column('provider_response_due_date', sa.String(length=10), nullable=True),
    sa.Column('is_sensitive_provider', sa.Boolean(), nullable=False),
    sa.Column('requires_supervisor_approval', sa.Boolean(), nullable=False),
    sa.Column('evidence_bundle', sa.Text(), nullable=False),
    sa.Column('case_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['assigned_analyst_id'], ['opa_users.user_id'], ),
    sa.ForeignKeyConstraint(['case_group_id'], ['case_groups.case_group_id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.claim_id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ),
    sa.ForeignKeyConstraint(['provider_org_id'], ['provider_orgs.provider_org_id'], ),
    sa.PrimaryKeyConstraint('case_id'),
    sa.UniqueConstraint('case_number')
    )
    op.create_table('audit_logs',
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('actor_user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('from_state', sa.String(length=50), nullable=True),
    sa.Column('to_state', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('meta_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['opa_users.user_id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['opa_cases.case_id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('disputes',
    sa.Column('dispute_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('received_date', sa.String(length=10), nullable=False),
    sa.Column('submitted_by_name', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('dispute_reason_code', sa.String(length=20), nullable=False),
    sa.Column('dispute_reason_text', sa.Text(), nullable=False),
    sa.Column('supporting_evidence_ref', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('resolution_date', sa.String(length=10), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['opa_cases.case_id'], ),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['opa_users.user_id'], ),
    sa.PrimaryKeyConstraint('dispute_id')
    )
    op.create_table('findings',
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('claim_id', sa.String(length=36), nullable=False),
    sa.Column('claim_line_id', sa.String(length=36), nullable=True),
    sa.Column('detector_id', sa.String(length=50), nullable=False),
    sa.Column('detector_version', sa.String(length=20), nullable=False),
    sa.Column('fired_at', sa.String(length=30), nullable=False),
    sa.Column('overpayment_amount', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('rule_version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.claim_id'], ),
    sa.ForeignKeyConstraint(['claim_line_id'], ['claim_lines.claim_line_id'], ),
    sa.PrimaryKeyConstraint('finding_id')
    )
    op.create_table('likelihood_scores',
    sa.Column('score_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('provider_risk_score', sa.Float(), nullable=False),
    sa.Column('cpt_risk_score', sa.Float(), nullable=False),
    sa.Column('dx_cpt_mismatch_score', sa.Float(), nullable=False),
    sa.Column('claim_complexity_score', sa.Float(), nullable=False),
    sa.Column('billing_variance_score', sa.Float(), nullable=False),
    sa.Column('composite_likelihood', sa.Float(), nullable=False),
    sa.Column('urgency_factor', sa.Float(), nullable=False),
    sa.Column('urgency_override_applied', sa.Boolean(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('score_json', sa.Text(), nullable=False),
    sa.Column('scored_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['opa_cases.case_id'], ),
    sa.PrimaryKeyConstraint('score_id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('provider_notices',
    sa.Column('notice_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=100), nullable=False),
    sa.Column('lob', sa.String(length=50), nullable=False),
    sa.Column('generated_at', sa.String(length=30), nullable=False),
    sa.Column('letter_content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('approved_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.String(length=30), nullable=True),
    sa.Column('sent_at', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['opa_users.user_id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['opa_cases.case_id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['letter_templates.template_id'], ),
    sa.PrimaryKeyConstraint('notice_id')
    )
    op.create_table('reconciliations',
    sa.Column('reconciliation_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('expected_amount', sa.Float(), nullable=False),
    sa.Column('actual_amount', sa.Float(), nullable=True),
    sa.Column('match_type', sa.String(length=30), nullable=False),
    sa.Column('recovery_835_transaction_id', sa.String(length=36), nullable=True),
    sa.Column('recovery_835_payment_id', sa.String(length=36), nullable=True),
    sa.Column('plb_reference', sa.String(length=100), nullable=True),
    sa.Column('treasury_reference', sa.String(length=100), nullable=True),
    sa.Column('exception_reason', sa.Text(), nullable=True),
    sa.Column('reconciled_at', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['opa_cases.case_id'], ),
    sa.ForeignKeyConstraint(['recovery_835_payment_id'], ['claim_payments_835.payment_id'], ),
    sa.ForeignKeyConstraint(['recovery_835_transaction_id'], ['transactions_835.transaction_id'], ),
    sa.PrimaryKeyConstraint('reconciliation_id')
    )
    op.create_table('recoupment_actions',
    sa.Column('recoupment_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('requested_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('submitted_at', sa.String(length=30), nullable=True),
    sa.Column('confirmed_at', sa.String(length=30), nullable=True),
    sa.Column('recovery_835_transaction_id', sa.String(length=36), nullable=True),
    sa.Column('staging_output_json', sa.Text(), nullable=False),
    sa.Column('staging_status', sa.String(length=30), nullable=False),
    sa.Column('staging_exported_at', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['opa_cases.case_id'], ),
    sa.ForeignKeyConstraint(['recovery_835_transaction_id'], ['transactions_835.transaction_id'], ),
    sa.PrimaryKeyConstraint('recoupment_id')
    )
    op.create_table('case_findings',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['opa_cases.case_id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.finding_id'], ),
    sa.PrimaryKeyConstraint('case_id', 'finding_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_findings')
    op.drop_table('recoupment_actions')
    op.drop_table('reconciliations')
    op.drop_table('provider_notices')
    op.drop_table('likelihood_scores')
    op.drop_table('findings')
    op.drop_table('disputes')
    op.drop_table('audit_logs')
    op.drop_table('opa_cases')
    op.drop_table('claim_lines')
    op.drop_table('claims')
    op.drop_table('claim_payments_835')
    op.drop_table('transactions_835')
    op.drop_table('providers')
    op.drop_table('letter_templates')
    op.drop_table('fee_schedules')
    op.drop_table('contract_limitations')
    op.drop_table('case_groups')
    op.drop_table('reference_data_freshness')
    op.drop_table('provider_orgs')
    op.drop_table('opa_users')
    op.drop_table('ml_model_versions')
    op.drop_table('members')
    op.drop_table('icd_codes')
    op.drop_table('cpt_icd_risks')
    op.drop_table('cpt_codes')
    op.drop_table('claim_headers_837')
    # ### end Alembic commands ###
