"""baseline squashed schema

Revision ID: 68c9293e51e1
Revises: 
Create Date: 2026-06-01 16:45:32.062843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '68c9293e51e1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apps',
    sa.Column('app_id', sa.String(length=36), nullable=False),
    sa.Column('app_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('app_id'),
    sa.UniqueConstraint('app_name')
    )
    op.create_table('claim_headers_837',
    sa.Column('header_id', sa.String(length=36), nullable=False),
    sa.Column('claim_icn', sa.String(length=100), nullable=False),
    sa.Column('submitter_npi', sa.String(length=20), nullable=False),
    sa.Column('billing_provider_npi', sa.String(length=20), nullable=False),
    sa.Column('submission_date', sa.String(length=10), nullable=False),
    sa.Column('total_billed', sa.Float(), nullable=False),
    sa.Column('claim_frequency_code', sa.String(length=5), nullable=False),
    sa.Column('raw_837_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('header_id'),
    sa.UniqueConstraint('claim_icn')
    )
    op.create_table('code_evidence_requirements',
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('code_type', sa.String(length=10), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('requirement_description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('requirement_id')
    )
    op.create_table('cpt_codes',
    sa.Column('cpt_code_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('value_tier', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('typical_units_max', sa.Integer(), nullable=False),
    sa.Column('requires_auth', sa.Boolean(), nullable=False),
    sa.Column('specialty_typical', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('cpt_code_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('cpt_icd_risks',
    sa.Column('cpt_icd_risk_id', sa.String(length=36), nullable=False),
    sa.Column('cpt_code', sa.String(length=10), nullable=False),
    sa.Column('icd_code', sa.String(length=10), nullable=False),
    sa.Column('mismatch_risk_score', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('cpt_icd_risk_id')
    )
    op.create_table('evidence_requirements',
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('code_type', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('required_evidence', sa.Text(), nullable=False),
    sa.Column('policy_reference', sa.String(length=255), nullable=False),
    sa.Column('severity_if_missing', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('requirement_id')
    )
    op.create_table('icd_codes',
    sa.Column('icd_code_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('value_tier', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('icd_code_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('members',
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('member_number', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.String(length=10), nullable=False),
    sa.Column('date_of_death', sa.String(length=10), nullable=True),
    sa.Column('lob', sa.String(length=50), nullable=False),
    sa.Column('coverage_effective_date', sa.String(length=10), nullable=False),
    sa.Column('coverage_termination_date', sa.String(length=10), nullable=True),
    sa.Column('retro_termination_date', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('member_id'),
    sa.UniqueConstraint('member_number')
    )
    op.create_table('ml_model_versions',
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_artifact_id', sa.String(length=255), nullable=False),
    sa.Column('trained_at', sa.String(length=30), nullable=False),
    sa.Column('training_rows', sa.Integer(), nullable=False),
    sa.Column('training_window', sa.String(length=50), nullable=False),
    sa.Column('training_params', sa.Text(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('precision_score', sa.Float(), nullable=True),
    sa.Column('recall_score', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('f2_score', sa.Float(), nullable=True),
    sa.Column('auc_roc', sa.Float(), nullable=True),
    sa.Column('decision_threshold', sa.Float(), nullable=True),
    sa.Column('positive_rate', sa.Float(), nullable=False),
    sa.Column('feature_importance', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_table('provider_orgs',
    sa.Column('provider_org_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('npi', sa.String(length=20), nullable=False),
    sa.Column('tin', sa.String(length=20), nullable=False),
    sa.Column('org_type', sa.String(length=50), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('provider_org_id'),
    sa.UniqueConstraint('npi')
    )
    op.create_table('reference_data_freshness',
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('last_refreshed_at', sa.String(length=30), nullable=False),
    sa.Column('next_scheduled_refresh', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('affected_detectors', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('source_name')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('case_groups',
    sa.Column('case_group_id', sa.String(length=36), nullable=False),
    sa.Column('group_number', sa.String(length=50), nullable=False),
    sa.Column('provider_org_id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('dos_range_start', sa.String(length=10), nullable=False),
    sa.Column('dos_range_end', sa.String(length=10), nullable=False),
    sa.Column('group_reason', sa.Text(), nullable=False),
    sa.Column('duplicate_suspected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ),
    sa.ForeignKeyConstraint(['provider_org_id'], ['provider_orgs.provider_org_id'], ),
    sa.PrimaryKeyConstraint('case_group_id'),
    sa.UniqueConstraint('group_number')
    )
    op.create_table('contract_limitations',
    sa.Column('limitation_id', sa.String(length=36), nullable=False),
    sa.Column('provider_org_id', sa.String(length=36), nullable=False),
    sa.Column('cpt_code', sa.String(length=10), nullable=False),
    sa.Column('limitation_type', sa.String(length=50), nullable=False),
    sa.Column('limitation_value', sa.String(length=100), nullable=False),
    sa.Column('effective_date', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['provider_org_id'], ['provider_orgs.provider_org_id'], ),
    sa.PrimaryKeyConstraint('limitation_id')
    )
    op.create_table('fee_schedules',
    sa.Column('fee_schedule_id', sa.String(length=36), nullable=False),
    sa.Column('provider_org_id', sa.String(length=36), nullable=False),
    sa.Column('lob', sa.String(length=50), nullable=False),
    sa.Column('cpt_code', sa.String(length=10), nullable=False),
    sa.Column('effective_date', sa.String(length=10), nullable=False),
    sa.Column('termination_date', sa.String(length=10), nullable=True),
    sa.Column('base_rate', sa.Float(), nullable=False),
    sa.Column('rate_basis', sa.String(length=50), nullable=False),
    sa.Column('modifier_applicable', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['provider_org_id'], ['provider_orgs.provider_org_id'], ),
    sa.PrimaryKeyConstraint('fee_schedule_id')
    )
    op.create_table('opa_users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('default_app_id', sa.String(length=36), nullable=True),
    sa.Column('initials', sa.String(length=10), nullable=True),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('specialty', sa.String(length=50), nullable=True),
    sa.Column('supervisor_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['default_app_id'], ['apps.app_id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['opa_users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('providers',
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('provider_org_id', sa.String(length=36), nullable=False),
    sa.Column('npi', sa.String(length=20), nullable=False),
    sa.Column('tin', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('credential_status', sa.String(length=50), nullable=False),
    sa.Column('credential_effective_date', sa.String(length=10), nullable=False),
    sa.Column('credential_lapse_date', sa.String(length=10), nullable=True),
    sa.Column('is_excluded', sa.Boolean(), nullable=False),
    sa.Column('exclusion_effective_date', sa.String(length=10), nullable=True),
    sa.Column('exclusion_source', sa.String(length=100), nullable=True),
    sa.Column('billing_variance_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['provider_org_id'], ['provider_orgs.provider_org_id'], ),
    sa.PrimaryKeyConstraint('provider_id'),
    sa.UniqueConstraint('npi')
    )
    op.create_table('role_apps',
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('app_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.app_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('role_id', 'app_id')
    )
    op.create_table('transactions_835',
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_number', sa.String(length=100), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('payer_name', sa.String(length=255), nullable=False),
    sa.Column('provider_org_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_date', sa.String(length=10), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('claim_count', sa.Integer(), nullable=False),
    sa.Column('raw_835_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['provider_org_id'], ['provider_orgs.provider_org_id'], ),
    sa.PrimaryKeyConstraint('transaction_id'),
    sa.UniqueConstraint('transaction_number')
    )
    op.create_table('claim_payments_835',
    sa.Column('payment_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('claim_icn', sa.String(length=100), nullable=False),
    sa.Column('cpt_code', sa.String(length=10), nullable=False),
    sa.Column('paid_amount', sa.Float(), nullable=False),
    sa.Column('adjustment_amount', sa.Float(), nullable=False),
    sa.Column('adjustment_reason_code', sa.String(length=20), nullable=True),
    sa.Column('check_number', sa.String(length=50), nullable=True),
    sa.Column('payment_date', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions_835.transaction_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_table('claims',
    sa.Column('claim_id', sa.String(length=36), nullable=False),
    sa.Column('icn', sa.String(length=100), nullable=False),
    sa.Column('case_group_id', sa.String(length=36), nullable=True),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('provider_org_id', sa.String(length=36), nullable=False),
    sa.Column('billing_provider_npi', sa.String(length=20), nullable=False),
    sa.Column('rendering_provider_npi', sa.String(length=20), nullable=False),
    sa.Column('lob', sa.String(length=50), nullable=False),
    sa.Column('pipeline_mode', sa.String(length=20), server_default='post_pay', nullable=False),
    sa.Column('service_from_date', sa.String(length=10), nullable=False),
    sa.Column('service_to_date', sa.String(length=10), nullable=False),
    sa.Column('claim_type', sa.String(length=50), nullable=False),
    sa.Column('claim_form_type', sa.String(length=20), nullable=True),
    sa.Column('care_setting', sa.String(length=20), nullable=True),
    sa.Column('drg', sa.String(length=10), nullable=True),
    sa.Column('specialty', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('claim_summary', sa.Text(), nullable=True),
    sa.Column('code_descriptions', sa.Text(), nullable=True),
    sa.Column('claim_status', sa.String(length=50), nullable=False),
    sa.Column('total_billed', sa.Float(), nullable=False),
    sa.Column('total_paid', sa.Float(), nullable=True),
    sa.Column('paid_date', sa.String(length=10), nullable=True),
    sa.Column('authorization_number', sa.String(length=50), nullable=True),
    sa.Column('submission_date', sa.String(length=10), nullable=False),
    sa.Column('pos_code', sa.String(length=5), nullable=False),
    sa.Column('primary_icd', sa.String(length=10), nullable=False),
    sa.Column('era_transaction_id', sa.String(length=36), nullable=True),
    sa.Column('raw_claim_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['case_group_id'], ['case_groups.case_group_id'], ),
    sa.ForeignKeyConstraint(['era_transaction_id'], ['transactions_835.transaction_id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ),
    sa.ForeignKeyConstraint(['provider_org_id'], ['provider_orgs.provider_org_id'], ),
    sa.PrimaryKeyConstraint('claim_id'),
    sa.UniqueConstraint('icn')
    )
    op.create_table('connectors',
    sa.Column('connector_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('secret_json', sa.Text(), nullable=False),
    sa.Column('input_schema_json', sa.Text(), nullable=True),
    sa.Column('mock_enabled', sa.Boolean(), nullable=False),
    sa.Column('mock_response_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['opa_users.user_id'], ),
    sa.PrimaryKeyConstraint('connector_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('detector_rule_config',
    sa.Column('rule_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.Column('updated_by_user_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['opa_users.user_id'], ),
    sa.PrimaryKeyConstraint('rule_code')
    )
    op.create_table('document_templates',
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('app', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_prompt', sa.Text(), nullable=False),
    sa.Column('template_markdown', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['opa_users.user_id'], ),
    sa.PrimaryKeyConstraint('template_id')
    )
    with op.batch_alter_table('document_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_templates_app'), ['app'], unique=False)

    op.create_table('letter_templates',
    sa.Column('template_id', sa.String(length=100), nullable=False),
    sa.Column('lob', sa.String(length=50), nullable=False),
    sa.Column('template_name', sa.String(length=255), nullable=False),
    sa.Column('regulatory_reference', sa.Text(), nullable=False),
    sa.Column('template_content', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['opa_users.user_id'], ),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_table('ml_training_config',
    sa.Column('config_id', sa.String(length=20), nullable=False),
    sa.Column('n_estimators', sa.Integer(), nullable=False),
    sa.Column('max_depth', sa.Integer(), nullable=True),
    sa.Column('min_samples_split', sa.Integer(), nullable=False),
    sa.Column('min_samples_leaf', sa.Integer(), nullable=False),
    sa.Column('max_features', sa.String(length=20), nullable=True),
    sa.Column('max_leaf_nodes', sa.Integer(), nullable=True),
    sa.Column('bootstrap', sa.Boolean(), nullable=False),
    sa.Column('class_weight', sa.String(length=30), nullable=True),
    sa.Column('criterion', sa.String(length=20), nullable=False),
    sa.Column('decision_threshold_mode', sa.String(length=20), nullable=False),
    sa.Column('manual_threshold', sa.Float(), nullable=True),
    sa.Column('min_auc_to_promote', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.Column('updated_by_user_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['opa_users.user_id'], ),
    sa.PrimaryKeyConstraint('config_id')
    )
    op.create_table('prioritization_config',
    sa.Column('config_id', sa.String(length=20), nullable=False),
    sa.Column('amount_weight', sa.Float(), nullable=False),
    sa.Column('likelihood_weight', sa.Float(), nullable=False),
    sa.Column('urgency_weight', sa.Float(), nullable=False),
    sa.Column('amount_cap', sa.Float(), nullable=False),
    sa.Column('urgency_window_days', sa.Integer(), nullable=False),
    sa.Column('high_threshold', sa.Float(), nullable=False),
    sa.Column('medium_threshold', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.Column('updated_by_user_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['opa_users.user_id'], ),
    sa.PrimaryKeyConstraint('config_id')
    )
    op.create_table('runtime_config',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.Column('updated_by_user_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['opa_users.user_id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('siu_investigations',
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('investigation_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('outcome', sa.String(length=40), nullable=True),
    sa.Column('closure_notes', sa.Text(), nullable=True),
    sa.Column('escalation_source', sa.String(length=40), nullable=False),
    sa.Column('escalation_reason', sa.Text(), nullable=False),
    sa.Column('escalated_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('escalated_at', sa.String(length=30), nullable=False),
    sa.Column('investigator_assigned_user_id', sa.String(length=36), nullable=True),
    sa.Column('opened_at', sa.String(length=30), nullable=True),
    sa.Column('closed_at', sa.String(length=30), nullable=True),
    sa.Column('closed_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('law_enforcement_hold', sa.Boolean(), nullable=False),
    sa.Column('siu_mode', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['closed_by_user_id'], ['opa_users.user_id'], ),
    sa.ForeignKeyConstraint(['escalated_by_user_id'], ['opa_users.user_id'], ),
    sa.ForeignKeyConstraint(['investigator_assigned_user_id'], ['opa_users.user_id'], ),
    sa.PrimaryKeyConstraint('investigation_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('granted_at', sa.String(length=30), nullable=False),
    sa.Column('granted_by_user_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['opa_users.user_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['opa_users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('claim_lines',
    sa.Column('claim_line_id', sa.String(length=36), nullable=False),
    sa.Column('claim_id', sa.String(length=36), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('cpt_code', sa.String(length=10), nullable=False),
    sa.Column('icd_codes', sa.Text(), nullable=False),
    sa.Column('modifier_1', sa.String(length=5), nullable=True),
    sa.Column('modifier_2', sa.String(length=5), nullable=True),
    sa.Column('units_billed', sa.Integer(), nullable=False),
    sa.Column('units_paid', sa.Integer(), nullable=True),
    sa.Column('billed_amount', sa.Float(), nullable=False),
    sa.Column('paid_amount', sa.Float(), nullable=True),
    sa.Column('allowed_amount', sa.Float(), nullable=True),
    sa.Column('pos_code', sa.String(length=5), nullable=False),
    sa.Column('revenue_code', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.claim_id'], ),
    sa.PrimaryKeyConstraint('claim_line_id')
    )
    op.create_table('connector_runs',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('connector_id', sa.String(length=36), nullable=False),
    sa.Column('triggered_at', sa.String(length=30), nullable=False),
    sa.Column('triggered_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('input_json', sa.Text(), nullable=True),
    sa.Column('output_json', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.connector_id'], ),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['opa_users.user_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('investigation_notes',
    sa.Column('note_id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('note_date', sa.String(length=10), nullable=False),
    sa.Column('note_type', sa.String(length=40), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_confidential', sa.Boolean(), nullable=False),
    sa.Column('author_user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['opa_users.user_id'], ),
    sa.ForeignKeyConstraint(['investigation_id'], ['siu_investigations.investigation_id'], ),
    sa.PrimaryKeyConstraint('note_id')
    )
    op.create_table('law_enforcement_referrals',
    sa.Column('referral_id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('referral_date', sa.String(length=10), nullable=False),
    sa.Column('agency_name', sa.String(length=100), nullable=False),
    sa.Column('referral_type', sa.String(length=30), nullable=False),
    sa.Column('referral_summary', sa.Text(), nullable=False),
    sa.Column('referral_contact_name', sa.String(length=255), nullable=False),
    sa.Column('submitted_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('submitted_at', sa.String(length=30), nullable=False),
    sa.Column('response_received_date', sa.String(length=10), nullable=True),
    sa.Column('referral_outcome', sa.String(length=20), nullable=True),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.Column('closed_at', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['siu_investigations.investigation_id'], ),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['opa_users.user_id'], ),
    sa.PrimaryKeyConstraint('referral_id')
    )
    op.create_table('opa_cases',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('case_number', sa.String(length=50), nullable=False),
    sa.Column('case_sequence', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.String(length=36), nullable=False),
    sa.Column('case_group_id', sa.String(length=36), nullable=True),
    sa.Column('primary_detector_id', sa.String(length=50), nullable=False),
    sa.Column('lob', sa.String(length=50), nullable=False),
    sa.Column('provider_org_id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_analyst_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('total_overpayment_amount', sa.Float(), nullable=True),
    sa.Column('review_time_minutes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('recommended_recovery_method', sa.String(length=50), nullable=False),
    sa.Column('identified_date', sa.String(length=10), nullable=False),
    sa.Column('deadline_date', sa.String(length=10), nullable=False),
    sa.Column('deadline_breached', sa.Boolean(), nullable=False),
    sa.Column('lookback_window_start', sa.String(length=10), nullable=False),
    sa.Column('provider_response_due_date', sa.String(length=10), nullable=True),
    sa.Column('is_sensitive_provider', sa.Boolean(), nullable=False),
    sa.Column('requires_supervisor_approval', sa.Boolean(), nullable=False),
    sa.Column('evidence_bundle', sa.Text(), nullable=False),
    sa.Column('case_json', sa.Text(), nullable=False),
    sa.Column('decision_metadata', sa.Text(), nullable=True),
    sa.Column('siu_investigation_id', sa.String(length=36), nullable=True),
    sa.Column('law_enforcement_hold', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('siu_frozen', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['assigned_analyst_id'], ['opa_users.user_id'], ),
    sa.ForeignKeyConstraint(['case_group_id'], ['case_groups.case_group_id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.claim_id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ),
    sa.ForeignKeyConstraint(['provider_org_id'], ['provider_orgs.provider_org_id'], ),
    sa.ForeignKeyConstraint(['siu_investigation_id'], ['siu_investigations.investigation_id'], ),
    sa.PrimaryKeyConstraint('case_id'),
    sa.UniqueConstraint('case_number')
    )
    op.create_table('siu_export_packages',
    sa.Column('package_id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('package_json', sa.Text(), nullable=False),
    sa.Column('integrity_hash', sa.String(length=64), nullable=False),
    sa.Column('generated_at', sa.String(length=30), nullable=False),
    sa.Column('generated_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('delivery_status', sa.String(length=20), nullable=False),
    sa.Column('delivery_destination', sa.String(length=255), nullable=True),
    sa.Column('delivery_attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.String(length=30), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['opa_users.user_id'], ),
    sa.ForeignKeyConstraint(['investigation_id'], ['siu_investigations.investigation_id'], ),
    sa.PrimaryKeyConstraint('package_id')
    )
    op.create_table('audit_logs',
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('claim_id', sa.String(length=36), nullable=True),
    sa.Column('actor_user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('from_state', sa.String(length=50), nullable=True),
    sa.Column('to_state', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('meta_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['opa_users.user_id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['opa_cases.case_id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.claim_id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('case_notes',
    sa.Column('note_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('author_user_id', sa.String(length=36), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['opa_users.user_id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['opa_cases.case_id'], ),
    sa.PrimaryKeyConstraint('note_id')
    )
    with op.batch_alter_table('case_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_notes_case_id'), ['case_id'], unique=False)

    op.create_table('contact_logs',
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('logged_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('contact_date', sa.String(length=10), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('direction', sa.String(length=15), nullable=False),
    sa.Column('participant_name', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['opa_cases.case_id'], ),
    sa.ForeignKeyConstraint(['logged_by_user_id'], ['opa_users.user_id'], ),
    sa.PrimaryKeyConstraint('contact_id')
    )
    with op.batch_alter_table('contact_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_logs_case_id'), ['case_id'], unique=False)

    op.create_table('disputes',
    sa.Column('dispute_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('received_date', sa.String(length=10), nullable=False),
    sa.Column('submitted_by_name', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('dispute_reason_code', sa.String(length=20), nullable=False),
    sa.Column('dispute_reason_text', sa.Text(), nullable=False),
    sa.Column('supporting_evidence_ref', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('resolution_date', sa.String(length=10), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['opa_cases.case_id'], ),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['opa_users.user_id'], ),
    sa.PrimaryKeyConstraint('dispute_id')
    )
    op.create_table('documents',
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('claim_id', sa.String(length=36), nullable=True),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('investigation_id', sa.String(length=36), nullable=True),
    sa.Column('investigation_note_id', sa.String(length=36), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_kb', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('uploaded_at', sa.String(length=30), nullable=False),
    sa.Column('uploaded_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extracted_at', sa.String(length=30), nullable=True),
    sa.Column('extraction_status', sa.String(length=20), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['opa_cases.case_id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.claim_id'], ),
    sa.ForeignKeyConstraint(['investigation_id'], ['siu_investigations.investigation_id'], ),
    sa.ForeignKeyConstraint(['investigation_note_id'], ['investigation_notes.note_id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['opa_users.user_id'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_claim_id'), ['claim_id'], unique=False)

    op.create_table('findings',
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('claim_id', sa.String(length=36), nullable=False),
    sa.Column('claim_line_id', sa.String(length=36), nullable=True),
    sa.Column('detector_id', sa.String(length=50), nullable=True),
    sa.Column('detector_version', sa.String(length=20), nullable=False),
    sa.Column('fired_at', sa.String(length=30), nullable=False),
    sa.Column('overpayment_amount', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('issue_summary', sa.Text(), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('rule_version', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('fwa_indicator', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('fwa_rule_code', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.claim_id'], ),
    sa.ForeignKeyConstraint(['claim_line_id'], ['claim_lines.claim_line_id'], ),
    sa.PrimaryKeyConstraint('finding_id')
    )
    op.create_table('investigation_cases',
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['opa_cases.case_id'], ),
    sa.ForeignKeyConstraint(['investigation_id'], ['siu_investigations.investigation_id'], ),
    sa.PrimaryKeyConstraint('investigation_id', 'case_id')
    )
    op.create_table('likelihood_scores',
    sa.Column('score_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('provider_risk_score', sa.Float(), nullable=False),
    sa.Column('cpt_risk_score', sa.Float(), nullable=False),
    sa.Column('dx_cpt_mismatch_score', sa.Float(), nullable=False),
    sa.Column('claim_complexity_score', sa.Float(), nullable=False),
    sa.Column('billing_variance_score', sa.Float(), nullable=False),
    sa.Column('composite_likelihood', sa.Float(), nullable=False),
    sa.Column('urgency_factor', sa.Float(), nullable=False),
    sa.Column('urgency_override_applied', sa.Boolean(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('score_json', sa.Text(), nullable=False),
    sa.Column('scored_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['opa_cases.case_id'], ),
    sa.PrimaryKeyConstraint('score_id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('notifications',
    sa.Column('notification_id', sa.String(length=36), nullable=False),
    sa.Column('recipient_user_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['opa_users.user_id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['opa_cases.case_id'], ),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['opa_users.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_recipient_created', ['recipient_user_id', 'created_at'], unique=False)
        batch_op.create_index('ix_notifications_recipient_unread', ['recipient_user_id', 'is_read'], unique=False)

    op.create_table('provider_notices',
    sa.Column('notice_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=100), nullable=False),
    sa.Column('lob', sa.String(length=50), nullable=False),
    sa.Column('generated_at', sa.String(length=30), nullable=False),
    sa.Column('letter_content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('approved_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.String(length=30), nullable=True),
    sa.Column('sent_at', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['opa_users.user_id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['opa_cases.case_id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['letter_templates.template_id'], ),
    sa.PrimaryKeyConstraint('notice_id')
    )
    op.create_table('reconciliations',
    sa.Column('reconciliation_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('expected_amount', sa.Float(), nullable=False),
    sa.Column('actual_amount', sa.Float(), nullable=True),
    sa.Column('match_type', sa.String(length=30), nullable=False),
    sa.Column('recovery_835_transaction_id', sa.String(length=36), nullable=True),
    sa.Column('recovery_835_payment_id', sa.String(length=36), nullable=True),
    sa.Column('plb_reference', sa.String(length=100), nullable=True),
    sa.Column('treasury_reference', sa.String(length=100), nullable=True),
    sa.Column('exception_reason', sa.Text(), nullable=True),
    sa.Column('reconciled_at', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['opa_cases.case_id'], ),
    sa.ForeignKeyConstraint(['recovery_835_payment_id'], ['claim_payments_835.payment_id'], ),
    sa.ForeignKeyConstraint(['recovery_835_transaction_id'], ['transactions_835.transaction_id'], ),
    sa.PrimaryKeyConstraint('reconciliation_id')
    )
    op.create_table('recoupment_actions',
    sa.Column('recoupment_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('requested_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('submitted_at', sa.String(length=30), nullable=True),
    sa.Column('confirmed_at', sa.String(length=30), nullable=True),
    sa.Column('recovery_835_transaction_id', sa.String(length=36), nullable=True),
    sa.Column('staging_output_json', sa.Text(), nullable=False),
    sa.Column('staging_status', sa.String(length=30), nullable=False),
    sa.Column('staging_exported_at', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['opa_cases.case_id'], ),
    sa.ForeignKeyConstraint(['recovery_835_transaction_id'], ['transactions_835.transaction_id'], ),
    sa.PrimaryKeyConstraint('recoupment_id')
    )
    op.create_table('case_findings',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['opa_cases.case_id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.finding_id'], ),
    sa.PrimaryKeyConstraint('case_id', 'finding_id')
    )
    op.create_table('evidence_findings',
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('claim_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('requirement_id', sa.String(length=36), nullable=True),
    sa.Column('code_type', sa.String(length=10), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_heading', sa.String(length=200), nullable=True),
    sa.Column('additional_sources', sa.Text(), server_default='[]', nullable=False),
    sa.Column('gap_description', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=80), nullable=True),
    sa.Column('scanned_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.claim_id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['code_evidence_requirements.requirement_id'], ),
    sa.PrimaryKeyConstraint('finding_id')
    )
    op.create_table('finding_dispositions',
    sa.Column('disposition_id', sa.String(length=36), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('original_amount', sa.Float(), nullable=False),
    sa.Column('adjusted_amount', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('decided_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('decided_at', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['opa_cases.case_id'], ),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['opa_users.user_id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.finding_id'], ),
    sa.PrimaryKeyConstraint('disposition_id'),
    sa.UniqueConstraint('finding_id')
    )
    with op.batch_alter_table('finding_dispositions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finding_dispositions_case_id'), ['case_id'], unique=False)

    op.create_table('prepay_finding_decisions',
    sa.Column('decision_id', sa.String(length=36), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('claim_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decided_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('decided_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.claim_id'], ),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['opa_users.user_id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.finding_id'], ),
    sa.PrimaryKeyConstraint('decision_id'),
    sa.UniqueConstraint('finding_id')
    )
    with op.batch_alter_table('prepay_finding_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prepay_finding_decisions_claim_id'), ['claim_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prepay_finding_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prepay_finding_decisions_claim_id'))

    op.drop_table('prepay_finding_decisions')
    with op.batch_alter_table('finding_dispositions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finding_dispositions_case_id'))

    op.drop_table('finding_dispositions')
    op.drop_table('evidence_findings')
    op.drop_table('case_findings')
    op.drop_table('recoupment_actions')
    op.drop_table('reconciliations')
    op.drop_table('provider_notices')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_recipient_unread')
        batch_op.drop_index('ix_notifications_recipient_created')

    op.drop_table('notifications')
    op.drop_table('likelihood_scores')
    op.drop_table('investigation_cases')
    op.drop_table('findings')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_claim_id'))
        batch_op.drop_index(batch_op.f('ix_documents_case_id'))

    op.drop_table('documents')
    op.drop_table('disputes')
    with op.batch_alter_table('contact_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_logs_case_id'))

    op.drop_table('contact_logs')
    with op.batch_alter_table('case_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_notes_case_id'))

    op.drop_table('case_notes')
    op.drop_table('audit_logs')
    op.drop_table('siu_export_packages')
    op.drop_table('opa_cases')
    op.drop_table('law_enforcement_referrals')
    op.drop_table('investigation_notes')
    op.drop_table('connector_runs')
    op.drop_table('claim_lines')
    op.drop_table('user_roles')
    op.drop_table('siu_investigations')
    op.drop_table('runtime_config')
    op.drop_table('prioritization_config')
    op.drop_table('ml_training_config')
    op.drop_table('letter_templates')
    with op.batch_alter_table('document_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_templates_app'))

    op.drop_table('document_templates')
    op.drop_table('detector_rule_config')
    op.drop_table('connectors')
    op.drop_table('claims')
    op.drop_table('claim_payments_835')
    op.drop_table('transactions_835')
    op.drop_table('role_apps')
    op.drop_table('providers')
    op.drop_table('opa_users')
    op.drop_table('fee_schedules')
    op.drop_table('contract_limitations')
    op.drop_table('case_groups')
    op.drop_table('roles')
    op.drop_table('reference_data_freshness')
    op.drop_table('provider_orgs')
    op.drop_table('ml_model_versions')
    op.drop_table('members')
    op.drop_table('icd_codes')
    op.drop_table('evidence_requirements')
    op.drop_table('cpt_icd_risks')
    op.drop_table('cpt_codes')
    op.drop_table('code_evidence_requirements')
    op.drop_table('claim_headers_837')
    op.drop_table('apps')
    # ### end Alembic commands ###
