"""add_bill_type_revenue_code_tables_and_claim_bill_type

Revision ID: a3014f73b8a9
Revises: o3d6e5f4g740
Create Date: 2026-06-04 17:40:48.164749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a3014f73b8a9'
down_revision: Union[str, None] = 'o3d6e5f4g740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_type_codes',
    sa.Column('bill_type_code_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('facility_type', sa.String(length=50), nullable=False),
    sa.Column('bill_classification', sa.String(length=50), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('audit_notes', sa.Text(), nullable=True),
    sa.Column('source_authority', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('bill_type_code_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('revenue_codes',
    sa.Column('revenue_code_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('typical_setting', sa.String(length=20), server_default='both', nullable=False),
    sa.Column('requires_units', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('audit_notes', sa.Text(), nullable=True),
    sa.Column('source_authority', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('revenue_code_id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bill_type', sa.String(length=4), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_column('bill_type')

    op.drop_table('revenue_codes')
    op.drop_table('bill_type_codes')
    # ### end Alembic commands ###
