"""add intake_files staging table

Revision ID: 007478bf8b33
Revises: ec9c2a76390a
Create Date: 2026-06-19 13:27:59.987561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '007478bf8b33'
down_revision: Union[str, None] = 'ec9c2a76390a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intake_files',
    sa.Column('intake_id', sa.String(length=36), nullable=False),
    sa.Column('app', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_kb', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.String(length=30), nullable=False),
    sa.Column('uploaded_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('extraction_status', sa.String(length=20), nullable=True),
    sa.Column('extracted_member_number', sa.String(length=50), nullable=True),
    sa.Column('extracted_member_name', sa.String(length=200), nullable=True),
    sa.Column('extracted_dob', sa.String(length=10), nullable=True),
    sa.Column('extracted_service_dates', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('candidate_case_ids', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('result_case_id', sa.String(length=36), nullable=True),
    sa.Column('result_claim_id', sa.String(length=36), nullable=True),
    sa.Column('result_document_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['result_case_id'], ['opa_cases.case_id'], name=op.f('fk_intake_files_result_case_id_opa_cases')),
    sa.ForeignKeyConstraint(['result_claim_id'], ['claims.claim_id'], name=op.f('fk_intake_files_result_claim_id_claims')),
    sa.ForeignKeyConstraint(['result_document_id'], ['documents.document_id'], name=op.f('fk_intake_files_result_document_id_documents')),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['opa_users.user_id'], name=op.f('fk_intake_files_uploaded_by_user_id_opa_users')),
    sa.PrimaryKeyConstraint('intake_id', name=op.f('pk_intake_files'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intake_files')
    # ### end Alembic commands ###
