"""add extracted_service_lines to intake_files

Revision ID: 0b517929dac3
Revises: 2871820523f5
Create Date: 2026-06-19 18:33:30.883456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0b517929dac3'
down_revision: Union[str, None] = '2871820523f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Plain nullable add → native SQLite ALTER TABLE ADD COLUMN, no table rebuild.
    op.add_column(
        'intake_files',
        sa.Column('extracted_service_lines', sa.Text(), nullable=True),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intake_files', schema=None) as batch_op:
        batch_op.drop_column('extracted_service_lines')

    # ### end Alembic commands ###
