"""add service_date (DOS) to claim_lines

Revision ID: 2871820523f5
Revises: 2bf2bb056356
Create Date: 2026-06-19 18:19:23.072022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2871820523f5'
down_revision: Union[str, None] = '2bf2bb056356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Plain nullable add → native SQLite ALTER TABLE ADD COLUMN, no table rebuild.
    op.add_column(
        'claim_lines',
        sa.Column('service_date', sa.String(length=10), nullable=True),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claim_lines', schema=None) as batch_op:
        batch_op.drop_column('service_date')

    # ### end Alembic commands ###
