"""add service_date (DOS) to claim_payments_835

Revision ID: 2bf2bb056356
Revises: 007478bf8b33
Create Date: 2026-06-19 17:51:21.813397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2bf2bb056356'
down_revision: Union[str, None] = '007478bf8b33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Plain nullable add → native SQLite ALTER TABLE ADD COLUMN, no table rebuild.
    op.add_column(
        'claim_payments_835',
        sa.Column('service_date', sa.String(length=10), nullable=True),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claim_payments_835', schema=None) as batch_op:
        batch_op.drop_column('service_date')

    # ### end Alembic commands ###
