"""add claims.dx_pending (awaiting-837 gate)

Revision ID: 43fcf8da4d61
Revises: 0b517929dac3
Create Date: 2026-06-21 00:21:39.921999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '43fcf8da4d61'
down_revision: Union[str, None] = '0b517929dac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dx_pending', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_column('dx_pending')

    # ### end Alembic commands ###
