"""provider_delivery_playbook_and_case_delivery_fields

Revision ID: 9b242fe2c587
Revises: 43fcf8da4d61
Create Date: 2026-06-23 23:17:47.911984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9b242fe2c587'
down_revision: Union[str, None] = '43fcf8da4d61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_delivery_playbooks',
    sa.Column('playbook_id', sa.String(length=36), nullable=False),
    sa.Column('provider_org_id', sa.String(length=36), nullable=False),
    sa.Column('delivery_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('target_url', sa.String(length=500), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('email_template_ref', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('auth_config', sa.JSON(), nullable=True),
    sa.Column('preflight_checks', sa.JSON(), nullable=True),
    sa.Column('navigation_steps', sa.JSON(), nullable=True),
    sa.Column('confirmation_config', sa.JSON(), nullable=True),
    sa.Column('failure_signals', sa.JSON(), nullable=True),
    sa.Column('post_run_config', sa.JSON(), nullable=True),
    sa.Column('last_validated_at', sa.String(length=30), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('updated_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.String(length=30), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.String(length=30), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['opa_users.user_id'], name=op.f('fk_provider_delivery_playbooks_created_by_id_opa_users')),
    sa.ForeignKeyConstraint(['provider_org_id'], ['provider_orgs.provider_org_id'], name=op.f('fk_provider_delivery_playbooks_provider_org_id_provider_orgs')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['opa_users.user_id'], name=op.f('fk_provider_delivery_playbooks_updated_by_id_opa_users')),
    sa.PrimaryKeyConstraint('playbook_id', name=op.f('pk_provider_delivery_playbooks')),
    sa.UniqueConstraint('provider_org_id', name=op.f('uq_provider_delivery_playbooks_provider_org_id'))
    )
    with op.batch_alter_table('opa_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_confirmation_ref', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('last_delivery_attempt_at', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opa_cases', schema=None) as batch_op:
        batch_op.drop_column('last_delivery_attempt_at')
        batch_op.drop_column('delivery_confirmation_ref')

    op.drop_table('provider_delivery_playbooks')
    # ### end Alembic commands ###
