"""add_cpt_coverage_gaps_table

Revision ID: 9c28676855fb
Revises: 57b24d8e3916
Create Date: 2026-06-05 11:26:04.727175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9c28676855fb'
down_revision: Union[str, None] = '57b24d8e3916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cpt_coverage_gaps',
    sa.Column('cpt_code', sa.String(length=10), nullable=False),
    sa.Column('first_seen_at', sa.String(length=30), nullable=False),
    sa.Column('last_seen_at', sa.String(length=30), nullable=False),
    sa.Column('seen_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('last_seen_claim_id', sa.String(length=36), nullable=True),
    sa.Column('needs_review', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('reviewed_at', sa.String(length=30), nullable=True),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('cpt_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cpt_coverage_gaps')
    # ### end Alembic commands ###
