"""add api_keys table

Revision ID: 9fe5c480c840
Revises: 9b242fe2c587
Create Date: 2026-06-24 18:58:41.201274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9fe5c480c840'
down_revision: Union[str, None] = '9b242fe2c587'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('api_key_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('last_used_at', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.String(length=30), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['opa_users.user_id'], name=op.f('fk_api_keys_user_id_opa_users')),
    sa.PrimaryKeyConstraint('api_key_id', name=op.f('pk_api_keys')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_api_keys_token_hash'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_keys')
    # ### end Alembic commands ###
