"""add case_chat_sessions

Revision ID: a7ccc064b26e
Revises: 9fe5c480c840
Create Date: 2026-06-30 11:20:06.917014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a7ccc064b26e'
down_revision: Union[str, None] = '9fe5c480c840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_chat_sessions',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('messages', sa.Text(), server_default='[]', nullable=False),
    sa.Column('created_at', sa.String(length=30), server_default="(datetime('now'))", nullable=False),
    sa.Column('updated_at', sa.String(length=30), server_default="(datetime('now'))", nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['opa_cases.case_id'], name=op.f('fk_case_chat_sessions_case_id_opa_cases')),
    sa.PrimaryKeyConstraint('case_id', name=op.f('pk_case_chat_sessions'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_chat_sessions')
    # ### end Alembic commands ###
