"""add_cpt_prior_auth_requirements

Revision ID: daf9dcc100fc
Revises: a7ccc064b26e
Create Date: 2026-06-30 15:58:38.127306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'daf9dcc100fc'
down_revision: Union[str, None] = 'a7ccc064b26e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cpt_prior_auth_requirements',
    sa.Column('cpt_code', sa.String(length=10), nullable=False),
    sa.Column('lob', sa.String(length=50), server_default='NULL', nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=150), server_default='Payer Medical Policy', nullable=False),
    sa.Column('effective_date', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('cpt_code', 'lob', name=op.f('pk_cpt_prior_auth_requirements'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cpt_prior_auth_requirements')
    # ### end Alembic commands ###
