"""prioritization_config_option_b_emv

Revision ID: eb3909b62b39
Revises: daf9dcc100fc
Create Date: 2026-06-30 19:36:10.089365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'eb3909b62b39'
down_revision: Union[str, None] = 'daf9dcc100fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prioritization_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('severity_weight', sa.Float(), server_default='0.95', nullable=False))
        batch_op.add_column(sa.Column('rule_leak', sa.Float(), server_default='0.03', nullable=False))
        batch_op.drop_column('likelihood_weight')
        batch_op.drop_column('amount_weight')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prioritization_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_weight', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('likelihood_weight', sa.FLOAT(), nullable=False))
        batch_op.drop_column('rule_leak')
        batch_op.drop_column('severity_weight')

    # ### end Alembic commands ###
