"""baseline squashed schema v2 (named constraints)

Revision ID: ec9c2a76390a
Revises: 
Create Date: 2026-06-09 17:32:45.361357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ec9c2a76390a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apps',
    sa.Column('app_id', sa.String(length=36), nullable=False),
    sa.Column('app_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('app_id', name=op.f('pk_apps')),
    sa.UniqueConstraint('app_name', name=op.f('uq_apps_app_name'))
    )
    op.create_table('bill_type_codes',
    sa.Column('bill_type_code_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('facility_type', sa.String(length=50), nullable=False),
    sa.Column('bill_classification', sa.String(length=50), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('audit_notes', sa.Text(), nullable=True),
    sa.Column('source_authority', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('bill_type_code_id', name=op.f('pk_bill_type_codes')),
    sa.UniqueConstraint('code', name=op.f('uq_bill_type_codes_code'))
    )
    op.create_table('code_evidence_requirements',
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('code_type', sa.String(length=10), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('requirement_description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('requirement_id', name=op.f('pk_code_evidence_requirements'))
    )
    op.create_table('cpt_codes',
    sa.Column('cpt_code_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('code_type', sa.String(length=10), server_default='cpt', nullable=False),
    sa.Column('value_tier', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('typical_units_max', sa.Integer(), nullable=False),
    sa.Column('requires_auth', sa.Boolean(), nullable=False),
    sa.Column('specialty_typical', sa.String(length=100), nullable=False),
    sa.Column('typical_setting', sa.String(length=20), server_default='professional', nullable=False),
    sa.Column('applicable_settings', sa.Text(), nullable=True),
    sa.Column('is_add_on', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('global_period_days', sa.Integer(), nullable=True),
    sa.Column('effective_date', sa.String(length=10), nullable=True),
    sa.Column('termination_date', sa.String(length=10), nullable=True),
    sa.Column('audit_notes', sa.Text(), nullable=True),
    sa.Column('source_authority', sa.String(length=100), nullable=True),
    sa.Column('source_document', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('last_reviewed_at', sa.String(length=10), nullable=True),
    sa.Column('data_confidence', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('data_confidence_notes', sa.Text(), nullable=True),
    sa.Column('rule_certainty', sa.String(length=20), server_default='mandatory', nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('cpt_code_id', name=op.f('pk_cpt_codes')),
    sa.UniqueConstraint('code', name=op.f('uq_cpt_codes_code'))
    )
    op.create_table('cpt_coverage_gaps',
    sa.Column('cpt_code', sa.String(length=10), nullable=False),
    sa.Column('first_seen_at', sa.String(length=30), nullable=False),
    sa.Column('last_seen_at', sa.String(length=30), nullable=False),
    sa.Column('seen_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('last_seen_claim_id', sa.String(length=36), nullable=True),
    sa.Column('needs_review', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('reviewed_at', sa.String(length=30), nullable=True),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('cpt_code', name=op.f('pk_cpt_coverage_gaps'))
    )
    op.create_table('drg_codes',
    sa.Column('drg_code_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('drg_type', sa.String(length=20), nullable=False),
    sa.Column('mdc', sa.String(length=10), nullable=True),
    sa.Column('mdc_description', sa.String(length=200), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('geometric_mean_los', sa.Float(), nullable=True),
    sa.Column('arithmetic_mean_los', sa.Float(), nullable=True),
    sa.Column('is_surgical', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('effective_fy', sa.String(length=10), nullable=True),
    sa.Column('termination_fy', sa.String(length=10), nullable=True),
    sa.Column('mcc_drg', sa.String(length=10), nullable=True),
    sa.Column('base_drg', sa.String(length=10), nullable=True),
    sa.Column('typical_principal_dx', sa.Text(), nullable=True),
    sa.Column('typical_procedures', sa.Text(), nullable=True),
    sa.Column('clinical_criteria', sa.Text(), nullable=True),
    sa.Column('audit_notes', sa.Text(), nullable=True),
    sa.Column('source_authority', sa.String(length=100), nullable=True),
    sa.Column('source_document', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('last_reviewed_at', sa.String(length=10), nullable=True),
    sa.Column('data_confidence', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('data_confidence_notes', sa.Text(), nullable=True),
    sa.Column('rule_certainty', sa.String(length=20), server_default='mandatory', nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('drg_code_id', name=op.f('pk_drg_codes')),
    sa.UniqueConstraint('code', name=op.f('uq_drg_codes_code'))
    )
    op.create_table('evidence_requirements',
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('code_type', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('required_evidence', sa.Text(), nullable=False),
    sa.Column('policy_reference', sa.String(length=255), nullable=False),
    sa.Column('severity_if_missing', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('requirement_id', name=op.f('pk_evidence_requirements'))
    )
    op.create_table('excluded_providers',
    sa.Column('excluded_provider_id', sa.String(length=36), nullable=False),
    sa.Column('npi', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('middle_name', sa.String(length=255), nullable=True),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('general_category', sa.String(length=100), nullable=True),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('upin', sa.String(length=20), nullable=True),
    sa.Column('dob', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=10), nullable=True),
    sa.Column('zip_code', sa.String(length=15), nullable=True),
    sa.Column('exclusion_type', sa.String(length=20), nullable=True),
    sa.Column('exclusion_date', sa.String(length=10), nullable=True),
    sa.Column('reinstate_date', sa.String(length=10), nullable=True),
    sa.Column('waiver_date', sa.String(length=10), nullable=True),
    sa.Column('waiver_state', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=100), server_default='OIG LEIE', nullable=False),
    sa.Column('created_at', sa.String(length=30), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('excluded_provider_id', name=op.f('pk_excluded_providers'))
    )
    with op.batch_alter_table('excluded_providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_excluded_providers_npi'), ['npi'], unique=False)

    op.create_table('icd_codes',
    sa.Column('icd_code_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('code_type', sa.String(length=10), server_default='icd10_cm', nullable=False),
    sa.Column('value_tier', sa.String(length=20), nullable=False),
    sa.Column('chapter', sa.String(length=100), nullable=True),
    sa.Column('is_manifestation', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_etiology', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('effective_date', sa.String(length=10), nullable=True),
    sa.Column('termination_date', sa.String(length=10), nullable=True),
    sa.Column('typical_setting', sa.String(length=20), server_default='both', nullable=False),
    sa.Column('applicable_settings', sa.Text(), nullable=True),
    sa.Column('typical_drg', sa.String(length=10), nullable=True),
    sa.Column('valid_as_primary_dx', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('audit_notes', sa.Text(), nullable=True),
    sa.Column('source_authority', sa.String(length=100), nullable=True),
    sa.Column('source_document', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('last_reviewed_at', sa.String(length=10), nullable=True),
    sa.Column('data_confidence', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('data_confidence_notes', sa.Text(), nullable=True),
    sa.Column('rule_certainty', sa.String(length=20), server_default='mandatory', nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('icd_code_id', name=op.f('pk_icd_codes')),
    sa.UniqueConstraint('code', name=op.f('uq_icd_codes_code'))
    )
    op.create_table('members',
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('member_number', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.String(length=10), nullable=False),
    sa.Column('date_of_death', sa.String(length=10), nullable=True),
    sa.Column('lob', sa.String(length=50), nullable=False),
    sa.Column('coverage_effective_date', sa.String(length=10), nullable=False),
    sa.Column('coverage_termination_date', sa.String(length=10), nullable=True),
    sa.Column('retro_termination_date', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('member_id', name=op.f('pk_members')),
    sa.UniqueConstraint('member_number', name=op.f('uq_members_member_number'))
    )
    op.create_table('ml_model_versions',
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_artifact_id', sa.String(length=255), nullable=False),
    sa.Column('trained_at', sa.String(length=30), nullable=False),
    sa.Column('training_rows', sa.Integer(), nullable=False),
    sa.Column('training_window', sa.String(length=50), nullable=False),
    sa.Column('training_params', sa.Text(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('precision_score', sa.Float(), nullable=True),
    sa.Column('recall_score', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('f2_score', sa.Float(), nullable=True),
    sa.Column('auc_roc', sa.Float(), nullable=True),
    sa.Column('decision_threshold', sa.Float(), nullable=True),
    sa.Column('positive_rate', sa.Float(), nullable=False),
    sa.Column('feature_importance', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('version_id', name=op.f('pk_ml_model_versions'))
    )
    op.create_table('modifier_codes',
    sa.Column('modifier_code_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('modifier_type', sa.String(length=30), nullable=False),
    sa.Column('applies_to', sa.String(length=10), nullable=False),
    sa.Column('payment_impact', sa.String(length=20), nullable=True),
    sa.Column('payment_factor', sa.Float(), nullable=True),
    sa.Column('ncci_override', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('requires_documentation', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('audit_risk_score', sa.Float(), nullable=False),
    sa.Column('valid_cpt_prefixes', sa.Text(), nullable=True),
    sa.Column('mutually_exclusive_with', sa.Text(), nullable=True),
    sa.Column('audit_notes', sa.Text(), nullable=True),
    sa.Column('source_authority', sa.String(length=100), nullable=True),
    sa.Column('source_document', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('last_reviewed_at', sa.String(length=10), nullable=True),
    sa.Column('data_confidence', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('data_confidence_notes', sa.Text(), nullable=True),
    sa.Column('rule_certainty', sa.String(length=20), server_default='mandatory', nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('modifier_code_id', name=op.f('pk_modifier_codes')),
    sa.UniqueConstraint('code', name=op.f('uq_modifier_codes_code'))
    )
    op.create_table('provider_orgs',
    sa.Column('provider_org_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('npi', sa.String(length=20), nullable=False),
    sa.Column('tin', sa.String(length=20), nullable=False),
    sa.Column('org_type', sa.String(length=50), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('provider_org_id', name=op.f('pk_provider_orgs')),
    sa.UniqueConstraint('npi', name=op.f('uq_provider_orgs_npi'))
    )
    op.create_table('reference_data_freshness',
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('last_refreshed_at', sa.String(length=30), nullable=False),
    sa.Column('next_scheduled_refresh', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('affected_detectors', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('source_name', name=op.f('pk_reference_data_freshness'))
    )
    op.create_table('revenue_codes',
    sa.Column('revenue_code_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('typical_setting', sa.String(length=20), server_default='both', nullable=False),
    sa.Column('requires_units', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('audit_notes', sa.Text(), nullable=True),
    sa.Column('source_authority', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('revenue_code_id', name=op.f('pk_revenue_codes')),
    sa.UniqueConstraint('code', name=op.f('uq_revenue_codes_code'))
    )
    op.create_table('roles',
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('role_id', name=op.f('pk_roles')),
    sa.UniqueConstraint('role_name', name=op.f('uq_roles_role_name'))
    )
    op.create_table('rule_prompts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('output_schema', sa.Text(), nullable=True),
    sa.Column('prompt_type', sa.String(length=30), server_default='evaluation', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('model', sa.String(length=80), server_default='claude-sonnet-4-6', nullable=False),
    sa.Column('temperature', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('last_edited_by', sa.String(length=100), nullable=True),
    sa.Column('last_edited_at', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('eval_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_prompts')),
    sa.UniqueConstraint('rule_id', 'prompt_type', 'version', name='uq_rule_prompts_rule_type_ver')
    )
    with op.batch_alter_table('rule_prompts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_prompts_rule_id'), ['rule_id'], unique=False)

    op.create_table('case_groups',
    sa.Column('case_group_id', sa.String(length=36), nullable=False),
    sa.Column('group_number', sa.String(length=50), nullable=False),
    sa.Column('provider_org_id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('dos_range_start', sa.String(length=10), nullable=False),
    sa.Column('dos_range_end', sa.String(length=10), nullable=False),
    sa.Column('group_reason', sa.Text(), nullable=False),
    sa.Column('duplicate_suspected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], name=op.f('fk_case_groups_member_id_members')),
    sa.ForeignKeyConstraint(['provider_org_id'], ['provider_orgs.provider_org_id'], name=op.f('fk_case_groups_provider_org_id_provider_orgs')),
    sa.PrimaryKeyConstraint('case_group_id', name=op.f('pk_case_groups')),
    sa.UniqueConstraint('group_number', name=op.f('uq_case_groups_group_number'))
    )
    op.create_table('contract_limitations',
    sa.Column('limitation_id', sa.String(length=36), nullable=False),
    sa.Column('provider_org_id', sa.String(length=36), nullable=False),
    sa.Column('cpt_code', sa.String(length=10), nullable=False),
    sa.Column('limitation_type', sa.String(length=50), nullable=False),
    sa.Column('limitation_value', sa.String(length=100), nullable=False),
    sa.Column('effective_date', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['provider_org_id'], ['provider_orgs.provider_org_id'], name=op.f('fk_contract_limitations_provider_org_id_provider_orgs')),
    sa.PrimaryKeyConstraint('limitation_id', name=op.f('pk_contract_limitations'))
    )
    op.create_table('cpt_dx_coverage',
    sa.Column('cpt_code', sa.String(length=10), nullable=False),
    sa.Column('icd_code', sa.String(length=10), nullable=False),
    sa.Column('coverage_type', sa.String(length=20), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('source_authority', sa.String(length=100), nullable=True),
    sa.Column('source_document', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('last_reviewed_at', sa.String(length=10), nullable=True),
    sa.Column('data_confidence', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('data_confidence_notes', sa.Text(), nullable=True),
    sa.Column('rule_certainty', sa.String(length=20), server_default='guideline', nullable=False),
    sa.ForeignKeyConstraint(['cpt_code'], ['cpt_codes.code'], name=op.f('fk_cpt_dx_coverage_cpt_code_cpt_codes')),
    sa.ForeignKeyConstraint(['icd_code'], ['icd_codes.code'], name=op.f('fk_cpt_dx_coverage_icd_code_icd_codes')),
    sa.PrimaryKeyConstraint('cpt_code', 'icd_code', name=op.f('pk_cpt_dx_coverage'))
    )
    op.create_table('cpt_modifier_map',
    sa.Column('cpt_code', sa.String(length=10), nullable=False),
    sa.Column('modifier_code', sa.String(length=5), nullable=False),
    sa.Column('payment_factor', sa.Float(), nullable=True),
    sa.Column('ncci_override', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source_authority', sa.String(length=100), nullable=True),
    sa.Column('source_document', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('last_reviewed_at', sa.String(length=10), nullable=True),
    sa.Column('data_confidence', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('data_confidence_notes', sa.Text(), nullable=True),
    sa.Column('rule_certainty', sa.String(length=20), server_default='mandatory', nullable=False),
    sa.ForeignKeyConstraint(['cpt_code'], ['cpt_codes.code'], name=op.f('fk_cpt_modifier_map_cpt_code_cpt_codes')),
    sa.ForeignKeyConstraint(['modifier_code'], ['modifier_codes.code'], name=op.f('fk_cpt_modifier_map_modifier_code_modifier_codes')),
    sa.PrimaryKeyConstraint('cpt_code', 'modifier_code', name=op.f('pk_cpt_modifier_map'))
    )
    op.create_table('fee_schedules',
    sa.Column('fee_schedule_id', sa.String(length=36), nullable=False),
    sa.Column('provider_org_id', sa.String(length=36), nullable=False),
    sa.Column('lob', sa.String(length=50), nullable=False),
    sa.Column('cpt_code', sa.String(length=10), nullable=False),
    sa.Column('effective_date', sa.String(length=10), nullable=False),
    sa.Column('termination_date', sa.String(length=10), nullable=True),
    sa.Column('base_rate', sa.Float(), nullable=False),
    sa.Column('rate_basis', sa.String(length=50), nullable=False),
    sa.Column('modifier_applicable', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['provider_org_id'], ['provider_orgs.provider_org_id'], name=op.f('fk_fee_schedules_provider_org_id_provider_orgs')),
    sa.PrimaryKeyConstraint('fee_schedule_id', name=op.f('pk_fee_schedules'))
    )
    op.create_table('opa_users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('default_app_id', sa.String(length=36), nullable=True),
    sa.Column('initials', sa.String(length=10), nullable=True),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('specialty', sa.String(length=50), nullable=True),
    sa.Column('supervisor_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['default_app_id'], ['apps.app_id'], name=op.f('fk_opa_users_default_app_id_apps')),
    sa.ForeignKeyConstraint(['supervisor_id'], ['opa_users.user_id'], name=op.f('fk_opa_users_supervisor_id_opa_users')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_opa_users')),
    sa.UniqueConstraint('username', name=op.f('uq_opa_users_username'))
    )
    op.create_table('providers',
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('provider_org_id', sa.String(length=36), nullable=False),
    sa.Column('npi', sa.String(length=20), nullable=False),
    sa.Column('tin', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('credential_status', sa.String(length=50), nullable=False),
    sa.Column('credential_effective_date', sa.String(length=10), nullable=False),
    sa.Column('credential_lapse_date', sa.String(length=10), nullable=True),
    sa.Column('is_excluded', sa.Boolean(), nullable=False),
    sa.Column('exclusion_effective_date', sa.String(length=10), nullable=True),
    sa.Column('exclusion_source', sa.String(length=100), nullable=True),
    sa.Column('billing_variance_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['provider_org_id'], ['provider_orgs.provider_org_id'], name=op.f('fk_providers_provider_org_id_provider_orgs')),
    sa.PrimaryKeyConstraint('provider_id', name=op.f('pk_providers')),
    sa.UniqueConstraint('npi', name=op.f('uq_providers_npi'))
    )
    op.create_table('role_apps',
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('app_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.app_id'], name=op.f('fk_role_apps_app_id_apps')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], name=op.f('fk_role_apps_role_id_roles')),
    sa.PrimaryKeyConstraint('role_id', 'app_id', name=op.f('pk_role_apps'))
    )
    op.create_table('transactions_835',
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_number', sa.String(length=100), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('payer_name', sa.String(length=255), nullable=False),
    sa.Column('provider_org_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_date', sa.String(length=10), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('claim_count', sa.Integer(), nullable=False),
    sa.Column('raw_835_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['provider_org_id'], ['provider_orgs.provider_org_id'], name=op.f('fk_transactions_835_provider_org_id_provider_orgs')),
    sa.PrimaryKeyConstraint('transaction_id', name=op.f('pk_transactions_835')),
    sa.UniqueConstraint('transaction_number', name=op.f('uq_transactions_835_transaction_number'))
    )
    op.create_table('claims',
    sa.Column('claim_id', sa.String(length=36), nullable=False),
    sa.Column('icn', sa.String(length=100), nullable=False),
    sa.Column('case_group_id', sa.String(length=36), nullable=True),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('provider_org_id', sa.String(length=36), nullable=False),
    sa.Column('billing_provider_npi', sa.String(length=20), nullable=False),
    sa.Column('rendering_provider_npi', sa.String(length=20), nullable=False),
    sa.Column('lob', sa.String(length=50), nullable=False),
    sa.Column('pipeline_mode', sa.String(length=20), server_default='post_pay', nullable=False),
    sa.Column('service_from_date', sa.String(length=10), nullable=False),
    sa.Column('service_to_date', sa.String(length=10), nullable=False),
    sa.Column('claim_type', sa.String(length=50), nullable=False),
    sa.Column('claim_form_type', sa.String(length=20), nullable=True),
    sa.Column('care_setting', sa.String(length=20), nullable=True),
    sa.Column('drg', sa.String(length=10), nullable=True),
    sa.Column('specialty', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('submitted_member_number', sa.String(length=50), nullable=True),
    sa.Column('submitted_patient_dob', sa.String(length=10), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('claim_summary', sa.Text(), nullable=True),
    sa.Column('code_descriptions', sa.Text(), nullable=True),
    sa.Column('claim_status', sa.String(length=50), nullable=False),
    sa.Column('total_billed', sa.Float(), nullable=False),
    sa.Column('total_paid', sa.Float(), nullable=True),
    sa.Column('paid_date', sa.String(length=10), nullable=True),
    sa.Column('authorization_number', sa.String(length=50), nullable=True),
    sa.Column('bill_type', sa.String(length=4), nullable=True),
    sa.Column('submission_date', sa.String(length=10), nullable=False),
    sa.Column('pos_code', sa.String(length=5), nullable=False),
    sa.Column('primary_icd', sa.String(length=10), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('submitter_npi', sa.String(length=20), nullable=True),
    sa.Column('claim_frequency_code', sa.String(length=5), nullable=True),
    sa.Column('era_transaction_id', sa.String(length=36), nullable=True),
    sa.Column('raw_claim_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['case_group_id'], ['case_groups.case_group_id'], name=op.f('fk_claims_case_group_id_case_groups')),
    sa.ForeignKeyConstraint(['era_transaction_id'], ['transactions_835.transaction_id'], name=op.f('fk_claims_era_transaction_id_transactions_835')),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], name=op.f('fk_claims_member_id_members')),
    sa.ForeignKeyConstraint(['provider_org_id'], ['provider_orgs.provider_org_id'], name=op.f('fk_claims_provider_org_id_provider_orgs')),
    sa.PrimaryKeyConstraint('claim_id', name=op.f('pk_claims')),
    sa.UniqueConstraint('icn', name=op.f('uq_claims_icn'))
    )
    op.create_table('connectors',
    sa.Column('connector_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('secret_json', sa.Text(), nullable=False),
    sa.Column('input_schema_json', sa.Text(), nullable=True),
    sa.Column('mock_enabled', sa.Boolean(), nullable=False),
    sa.Column('mock_response_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['opa_users.user_id'], name=op.f('fk_connectors_created_by_user_id_opa_users')),
    sa.PrimaryKeyConstraint('connector_id', name=op.f('pk_connectors')),
    sa.UniqueConstraint('name', name=op.f('uq_connectors_name'))
    )
    op.create_table('detector_rule_config',
    sa.Column('rule_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('enabled_prepay', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('enabled_postpay', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('layer', sa.String(length=60), nullable=True),
    sa.Column('layer_order', sa.Integer(), nullable=True),
    sa.Column('applies_to', sa.String(length=30), server_default='Both', nullable=True),
    sa.Column('default_disposition', sa.String(length=30), server_default='suspend_review', nullable=True),
    sa.Column('has_implementation', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('prepay', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('postpay', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.Column('updated_by_user_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['opa_users.user_id'], name=op.f('fk_detector_rule_config_updated_by_user_id_opa_users')),
    sa.PrimaryKeyConstraint('rule_code', name=op.f('pk_detector_rule_config'))
    )
    op.create_table('document_templates',
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('app', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_prompt', sa.Text(), nullable=False),
    sa.Column('template_markdown', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['opa_users.user_id'], name=op.f('fk_document_templates_created_by_user_id_opa_users')),
    sa.PrimaryKeyConstraint('template_id', name=op.f('pk_document_templates'))
    )
    with op.batch_alter_table('document_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_templates_app'), ['app'], unique=False)

    op.create_table('letter_templates',
    sa.Column('template_id', sa.String(length=100), nullable=False),
    sa.Column('lob', sa.String(length=50), nullable=False),
    sa.Column('template_name', sa.String(length=255), nullable=False),
    sa.Column('regulatory_reference', sa.Text(), nullable=False),
    sa.Column('template_content', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['opa_users.user_id'], name=op.f('fk_letter_templates_created_by_user_id_opa_users')),
    sa.PrimaryKeyConstraint('template_id', name=op.f('pk_letter_templates'))
    )
    op.create_table('ml_training_config',
    sa.Column('config_id', sa.String(length=20), nullable=False),
    sa.Column('n_estimators', sa.Integer(), nullable=False),
    sa.Column('max_depth', sa.Integer(), nullable=True),
    sa.Column('min_samples_split', sa.Integer(), nullable=False),
    sa.Column('min_samples_leaf', sa.Integer(), nullable=False),
    sa.Column('max_features', sa.String(length=20), nullable=True),
    sa.Column('max_leaf_nodes', sa.Integer(), nullable=True),
    sa.Column('bootstrap', sa.Boolean(), nullable=False),
    sa.Column('class_weight', sa.String(length=30), nullable=True),
    sa.Column('criterion', sa.String(length=20), nullable=False),
    sa.Column('decision_threshold_mode', sa.String(length=20), nullable=False),
    sa.Column('manual_threshold', sa.Float(), nullable=True),
    sa.Column('min_auc_to_promote', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.Column('updated_by_user_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['opa_users.user_id'], name=op.f('fk_ml_training_config_updated_by_user_id_opa_users')),
    sa.PrimaryKeyConstraint('config_id', name=op.f('pk_ml_training_config'))
    )
    op.create_table('prioritization_config',
    sa.Column('config_id', sa.String(length=20), nullable=False),
    sa.Column('amount_weight', sa.Float(), nullable=False),
    sa.Column('likelihood_weight', sa.Float(), nullable=False),
    sa.Column('urgency_weight', sa.Float(), nullable=False),
    sa.Column('amount_cap', sa.Float(), nullable=False),
    sa.Column('urgency_window_days', sa.Integer(), nullable=False),
    sa.Column('high_threshold', sa.Float(), nullable=False),
    sa.Column('medium_threshold', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.Column('updated_by_user_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['opa_users.user_id'], name=op.f('fk_prioritization_config_updated_by_user_id_opa_users')),
    sa.PrimaryKeyConstraint('config_id', name=op.f('pk_prioritization_config'))
    )
    op.create_table('runtime_config',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.Column('updated_by_user_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['opa_users.user_id'], name=op.f('fk_runtime_config_updated_by_user_id_opa_users')),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_runtime_config'))
    )
    op.create_table('siu_investigations',
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('investigation_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('outcome', sa.String(length=40), nullable=True),
    sa.Column('closure_notes', sa.Text(), nullable=True),
    sa.Column('escalation_source', sa.String(length=40), nullable=False),
    sa.Column('escalation_reason', sa.Text(), nullable=False),
    sa.Column('escalated_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('escalated_at', sa.String(length=30), nullable=False),
    sa.Column('investigator_assigned_user_id', sa.String(length=36), nullable=True),
    sa.Column('opened_at', sa.String(length=30), nullable=True),
    sa.Column('closed_at', sa.String(length=30), nullable=True),
    sa.Column('closed_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('law_enforcement_hold', sa.Boolean(), nullable=False),
    sa.Column('siu_mode', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['closed_by_user_id'], ['opa_users.user_id'], name=op.f('fk_siu_investigations_closed_by_user_id_opa_users')),
    sa.ForeignKeyConstraint(['escalated_by_user_id'], ['opa_users.user_id'], name=op.f('fk_siu_investigations_escalated_by_user_id_opa_users')),
    sa.ForeignKeyConstraint(['investigator_assigned_user_id'], ['opa_users.user_id'], name=op.f('fk_siu_investigations_investigator_assigned_user_id_opa_users')),
    sa.PrimaryKeyConstraint('investigation_id', name=op.f('pk_siu_investigations'))
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('granted_at', sa.String(length=30), nullable=False),
    sa.Column('granted_by_user_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['opa_users.user_id'], name=op.f('fk_user_roles_granted_by_user_id_opa_users')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], name=op.f('fk_user_roles_role_id_roles')),
    sa.ForeignKeyConstraint(['user_id'], ['opa_users.user_id'], name=op.f('fk_user_roles_user_id_opa_users')),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('claim_lines',
    sa.Column('claim_line_id', sa.String(length=36), nullable=False),
    sa.Column('claim_id', sa.String(length=36), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('cpt_code', sa.String(length=10), nullable=False),
    sa.Column('diag_1', sa.String(length=10), nullable=True),
    sa.Column('diag_2', sa.String(length=10), nullable=True),
    sa.Column('diag_3', sa.String(length=10), nullable=True),
    sa.Column('diag_4', sa.String(length=10), nullable=True),
    sa.Column('modifier_1', sa.String(length=5), nullable=True),
    sa.Column('modifier_2', sa.String(length=5), nullable=True),
    sa.Column('modifier_3', sa.String(length=5), nullable=True),
    sa.Column('modifier_4', sa.String(length=5), nullable=True),
    sa.Column('units_billed', sa.Integer(), nullable=False),
    sa.Column('units_paid', sa.Integer(), nullable=True),
    sa.Column('billed_amount', sa.Float(), nullable=False),
    sa.Column('paid_amount', sa.Float(), nullable=True),
    sa.Column('allowed_amount', sa.Float(), nullable=True),
    sa.Column('pos_code', sa.String(length=5), nullable=False),
    sa.Column('revenue_code', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.claim_id'], name=op.f('fk_claim_lines_claim_id_claims')),
    sa.PrimaryKeyConstraint('claim_line_id', name=op.f('pk_claim_lines'))
    )
    op.create_table('connector_runs',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('connector_id', sa.String(length=36), nullable=False),
    sa.Column('triggered_at', sa.String(length=30), nullable=False),
    sa.Column('triggered_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('input_json', sa.Text(), nullable=True),
    sa.Column('output_json', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.connector_id'], name=op.f('fk_connector_runs_connector_id_connectors')),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['opa_users.user_id'], name=op.f('fk_connector_runs_triggered_by_user_id_opa_users')),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_connector_runs'))
    )
    op.create_table('investigation_notes',
    sa.Column('note_id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('note_date', sa.String(length=10), nullable=False),
    sa.Column('note_type', sa.String(length=40), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_confidential', sa.Boolean(), nullable=False),
    sa.Column('author_user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['opa_users.user_id'], name=op.f('fk_investigation_notes_author_user_id_opa_users')),
    sa.ForeignKeyConstraint(['investigation_id'], ['siu_investigations.investigation_id'], name=op.f('fk_investigation_notes_investigation_id_siu_investigations')),
    sa.PrimaryKeyConstraint('note_id', name=op.f('pk_investigation_notes'))
    )
    op.create_table('law_enforcement_referrals',
    sa.Column('referral_id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('referral_date', sa.String(length=10), nullable=False),
    sa.Column('agency_name', sa.String(length=100), nullable=False),
    sa.Column('referral_type', sa.String(length=30), nullable=False),
    sa.Column('referral_summary', sa.Text(), nullable=False),
    sa.Column('referral_contact_name', sa.String(length=255), nullable=False),
    sa.Column('submitted_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('submitted_at', sa.String(length=30), nullable=False),
    sa.Column('response_received_date', sa.String(length=10), nullable=True),
    sa.Column('referral_outcome', sa.String(length=20), nullable=True),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.Column('closed_at', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['siu_investigations.investigation_id'], name=op.f('fk_law_enforcement_referrals_investigation_id_siu_investigations')),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['opa_users.user_id'], name=op.f('fk_law_enforcement_referrals_submitted_by_user_id_opa_users')),
    sa.PrimaryKeyConstraint('referral_id', name=op.f('pk_law_enforcement_referrals'))
    )
    op.create_table('opa_cases',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('case_number', sa.String(length=50), nullable=False),
    sa.Column('case_sequence', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.String(length=36), nullable=False),
    sa.Column('case_group_id', sa.String(length=36), nullable=True),
    sa.Column('primary_detector_id', sa.String(length=50), nullable=False),
    sa.Column('lob', sa.String(length=50), nullable=False),
    sa.Column('provider_org_id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_analyst_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('pipeline_mode', sa.String(length=20), server_default='post_pay', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('total_overpayment_amount', sa.Float(), nullable=True),
    sa.Column('review_time_minutes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('recommended_recovery_method', sa.String(length=50), nullable=False),
    sa.Column('identified_date', sa.String(length=10), nullable=False),
    sa.Column('deadline_date', sa.String(length=10), nullable=False),
    sa.Column('deadline_breached', sa.Boolean(), nullable=False),
    sa.Column('lookback_window_start', sa.String(length=10), nullable=False),
    sa.Column('provider_response_due_date', sa.String(length=10), nullable=True),
    sa.Column('is_sensitive_provider', sa.Boolean(), nullable=False),
    sa.Column('requires_supervisor_approval', sa.Boolean(), nullable=False),
    sa.Column('evidence_bundle', sa.Text(), nullable=False),
    sa.Column('case_json', sa.Text(), nullable=False),
    sa.Column('decision_metadata', sa.Text(), nullable=True),
    sa.Column('siu_investigation_id', sa.String(length=36), nullable=True),
    sa.Column('law_enforcement_hold', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('siu_frozen', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['assigned_analyst_id'], ['opa_users.user_id'], name=op.f('fk_opa_cases_assigned_analyst_id_opa_users')),
    sa.ForeignKeyConstraint(['case_group_id'], ['case_groups.case_group_id'], name=op.f('fk_opa_cases_case_group_id_case_groups')),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.claim_id'], name=op.f('fk_opa_cases_claim_id_claims')),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], name=op.f('fk_opa_cases_member_id_members')),
    sa.ForeignKeyConstraint(['provider_org_id'], ['provider_orgs.provider_org_id'], name=op.f('fk_opa_cases_provider_org_id_provider_orgs')),
    sa.ForeignKeyConstraint(['siu_investigation_id'], ['siu_investigations.investigation_id'], name=op.f('fk_opa_cases_siu_investigation_id_siu_investigations')),
    sa.PrimaryKeyConstraint('case_id', name=op.f('pk_opa_cases')),
    sa.UniqueConstraint('case_number', name=op.f('uq_opa_cases_case_number'))
    )
    op.create_table('siu_export_packages',
    sa.Column('package_id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('package_json', sa.Text(), nullable=False),
    sa.Column('integrity_hash', sa.String(length=64), nullable=False),
    sa.Column('generated_at', sa.String(length=30), nullable=False),
    sa.Column('generated_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('delivery_status', sa.String(length=20), nullable=False),
    sa.Column('delivery_destination', sa.String(length=255), nullable=True),
    sa.Column('delivery_attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.String(length=30), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['opa_users.user_id'], name=op.f('fk_siu_export_packages_generated_by_user_id_opa_users')),
    sa.ForeignKeyConstraint(['investigation_id'], ['siu_investigations.investigation_id'], name=op.f('fk_siu_export_packages_investigation_id_siu_investigations')),
    sa.PrimaryKeyConstraint('package_id', name=op.f('pk_siu_export_packages'))
    )
    op.create_table('audit_logs',
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('claim_id', sa.String(length=36), nullable=True),
    sa.Column('actor_user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('from_state', sa.String(length=50), nullable=True),
    sa.Column('to_state', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('meta_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['opa_users.user_id'], name=op.f('fk_audit_logs_actor_user_id_opa_users')),
    sa.ForeignKeyConstraint(['case_id'], ['opa_cases.case_id'], name=op.f('fk_audit_logs_case_id_opa_cases')),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.claim_id'], name=op.f('fk_audit_logs_claim_id_claims')),
    sa.PrimaryKeyConstraint('audit_id', name=op.f('pk_audit_logs'))
    )
    op.create_table('case_notes',
    sa.Column('note_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('author_user_id', sa.String(length=36), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['opa_users.user_id'], name=op.f('fk_case_notes_author_user_id_opa_users')),
    sa.ForeignKeyConstraint(['case_id'], ['opa_cases.case_id'], name=op.f('fk_case_notes_case_id_opa_cases')),
    sa.PrimaryKeyConstraint('note_id', name=op.f('pk_case_notes'))
    )
    with op.batch_alter_table('case_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_notes_case_id'), ['case_id'], unique=False)

    op.create_table('claim_payments_835',
    sa.Column('payment_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('claim_icn', sa.String(length=100), nullable=False),
    sa.Column('claim_id', sa.String(length=36), nullable=True),
    sa.Column('claim_line_id', sa.String(length=36), nullable=True),
    sa.Column('cpt_code', sa.String(length=10), nullable=False),
    sa.Column('paid_amount', sa.Float(), nullable=False),
    sa.Column('adjustment_amount', sa.Float(), nullable=False),
    sa.Column('check_number', sa.String(length=50), nullable=True),
    sa.Column('payment_date', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.claim_id'], name=op.f('fk_claim_payments_835_claim_id_claims')),
    sa.ForeignKeyConstraint(['claim_line_id'], ['claim_lines.claim_line_id'], name=op.f('fk_claim_payments_835_claim_line_id_claim_lines')),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions_835.transaction_id'], name=op.f('fk_claim_payments_835_transaction_id_transactions_835')),
    sa.PrimaryKeyConstraint('payment_id', name=op.f('pk_claim_payments_835'))
    )
    op.create_table('contact_logs',
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('logged_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('contact_date', sa.String(length=10), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('direction', sa.String(length=15), nullable=False),
    sa.Column('participant_name', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['opa_cases.case_id'], name=op.f('fk_contact_logs_case_id_opa_cases')),
    sa.ForeignKeyConstraint(['logged_by_user_id'], ['opa_users.user_id'], name=op.f('fk_contact_logs_logged_by_user_id_opa_users')),
    sa.PrimaryKeyConstraint('contact_id', name=op.f('pk_contact_logs'))
    )
    with op.batch_alter_table('contact_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_logs_case_id'), ['case_id'], unique=False)

    op.create_table('disputes',
    sa.Column('dispute_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('received_date', sa.String(length=10), nullable=False),
    sa.Column('submitted_by_name', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('dispute_reason_code', sa.String(length=20), nullable=False),
    sa.Column('dispute_reason_text', sa.Text(), nullable=False),
    sa.Column('supporting_evidence_ref', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('resolution_date', sa.String(length=10), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['opa_cases.case_id'], name=op.f('fk_disputes_case_id_opa_cases')),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['opa_users.user_id'], name=op.f('fk_disputes_resolved_by_user_id_opa_users')),
    sa.PrimaryKeyConstraint('dispute_id', name=op.f('pk_disputes'))
    )
    op.create_table('documents',
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('claim_id', sa.String(length=36), nullable=True),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('investigation_id', sa.String(length=36), nullable=True),
    sa.Column('investigation_note_id', sa.String(length=36), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_kb', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('uploaded_at', sa.String(length=30), nullable=False),
    sa.Column('uploaded_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extracted_at', sa.String(length=30), nullable=True),
    sa.Column('extraction_status', sa.String(length=20), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['opa_cases.case_id'], name=op.f('fk_documents_case_id_opa_cases')),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.claim_id'], name=op.f('fk_documents_claim_id_claims')),
    sa.ForeignKeyConstraint(['investigation_id'], ['siu_investigations.investigation_id'], name=op.f('fk_documents_investigation_id_siu_investigations')),
    sa.ForeignKeyConstraint(['investigation_note_id'], ['investigation_notes.note_id'], name=op.f('fk_documents_investigation_note_id_investigation_notes')),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['opa_users.user_id'], name=op.f('fk_documents_uploaded_by_user_id_opa_users')),
    sa.PrimaryKeyConstraint('document_id', name=op.f('pk_documents'))
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_claim_id'), ['claim_id'], unique=False)

    op.create_table('findings',
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('claim_id', sa.String(length=36), nullable=False),
    sa.Column('claim_line_id', sa.String(length=36), nullable=True),
    sa.Column('detector_id', sa.String(length=50), nullable=True),
    sa.Column('detector_version', sa.String(length=20), nullable=False),
    sa.Column('fired_at', sa.String(length=30), nullable=False),
    sa.Column('overpayment_amount', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('issue_summary', sa.Text(), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('rule_version', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('fwa_indicator', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('fwa_rule_code', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.claim_id'], name=op.f('fk_findings_claim_id_claims')),
    sa.ForeignKeyConstraint(['claim_line_id'], ['claim_lines.claim_line_id'], name=op.f('fk_findings_claim_line_id_claim_lines')),
    sa.PrimaryKeyConstraint('finding_id', name=op.f('pk_findings'))
    )
    op.create_table('investigation_cases',
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['opa_cases.case_id'], name=op.f('fk_investigation_cases_case_id_opa_cases')),
    sa.ForeignKeyConstraint(['investigation_id'], ['siu_investigations.investigation_id'], name=op.f('fk_investigation_cases_investigation_id_siu_investigations')),
    sa.PrimaryKeyConstraint('investigation_id', 'case_id', name=op.f('pk_investigation_cases'))
    )
    op.create_table('likelihood_scores',
    sa.Column('score_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('provider_risk_score', sa.Float(), nullable=False),
    sa.Column('cpt_risk_score', sa.Float(), nullable=False),
    sa.Column('dx_cpt_mismatch_score', sa.Float(), nullable=False),
    sa.Column('claim_complexity_score', sa.Float(), nullable=False),
    sa.Column('billing_variance_score', sa.Float(), nullable=False),
    sa.Column('composite_likelihood', sa.Float(), nullable=False),
    sa.Column('urgency_factor', sa.Float(), nullable=False),
    sa.Column('urgency_override_applied', sa.Boolean(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('score_json', sa.Text(), nullable=False),
    sa.Column('scored_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['opa_cases.case_id'], name=op.f('fk_likelihood_scores_case_id_opa_cases')),
    sa.PrimaryKeyConstraint('score_id', name=op.f('pk_likelihood_scores')),
    sa.UniqueConstraint('case_id', name=op.f('uq_likelihood_scores_case_id'))
    )
    op.create_table('notifications',
    sa.Column('notification_id', sa.String(length=36), nullable=False),
    sa.Column('recipient_user_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['opa_users.user_id'], name=op.f('fk_notifications_actor_user_id_opa_users')),
    sa.ForeignKeyConstraint(['case_id'], ['opa_cases.case_id'], name=op.f('fk_notifications_case_id_opa_cases')),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['opa_users.user_id'], name=op.f('fk_notifications_recipient_user_id_opa_users')),
    sa.PrimaryKeyConstraint('notification_id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_recipient_created', ['recipient_user_id', 'created_at'], unique=False)
        batch_op.create_index('ix_notifications_recipient_unread', ['recipient_user_id', 'is_read'], unique=False)

    op.create_table('provider_notices',
    sa.Column('notice_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=100), nullable=False),
    sa.Column('lob', sa.String(length=50), nullable=False),
    sa.Column('generated_at', sa.String(length=30), nullable=False),
    sa.Column('letter_content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('approved_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.String(length=30), nullable=True),
    sa.Column('sent_at', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['opa_users.user_id'], name=op.f('fk_provider_notices_approved_by_user_id_opa_users')),
    sa.ForeignKeyConstraint(['case_id'], ['opa_cases.case_id'], name=op.f('fk_provider_notices_case_id_opa_cases')),
    sa.ForeignKeyConstraint(['template_id'], ['letter_templates.template_id'], name=op.f('fk_provider_notices_template_id_letter_templates')),
    sa.PrimaryKeyConstraint('notice_id', name=op.f('pk_provider_notices'))
    )
    op.create_table('recoupment_actions',
    sa.Column('recoupment_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('requested_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('submitted_at', sa.String(length=30), nullable=True),
    sa.Column('confirmed_at', sa.String(length=30), nullable=True),
    sa.Column('recovery_835_transaction_id', sa.String(length=36), nullable=True),
    sa.Column('staging_output_json', sa.Text(), nullable=False),
    sa.Column('staging_status', sa.String(length=30), nullable=False),
    sa.Column('staging_exported_at', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['opa_cases.case_id'], name=op.f('fk_recoupment_actions_case_id_opa_cases')),
    sa.ForeignKeyConstraint(['recovery_835_transaction_id'], ['transactions_835.transaction_id'], name=op.f('fk_recoupment_actions_recovery_835_transaction_id_transactions_835')),
    sa.PrimaryKeyConstraint('recoupment_id', name=op.f('pk_recoupment_actions'))
    )
    op.create_table('case_findings',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['opa_cases.case_id'], name=op.f('fk_case_findings_case_id_opa_cases')),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.finding_id'], name=op.f('fk_case_findings_finding_id_findings')),
    sa.PrimaryKeyConstraint('case_id', 'finding_id', name=op.f('pk_case_findings'))
    )
    op.create_table('era_adjustment_codes',
    sa.Column('adjustment_id', sa.String(length=36), nullable=False),
    sa.Column('payment_id', sa.String(length=36), nullable=False),
    sa.Column('group_code', sa.String(length=2), nullable=False),
    sa.Column('reason_code', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['claim_payments_835.payment_id'], name=op.f('fk_era_adjustment_codes_payment_id_claim_payments_835')),
    sa.PrimaryKeyConstraint('adjustment_id', name=op.f('pk_era_adjustment_codes'))
    )
    op.create_table('evidence_findings',
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('claim_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('requirement_id', sa.String(length=36), nullable=True),
    sa.Column('code_type', sa.String(length=10), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_heading', sa.String(length=200), nullable=True),
    sa.Column('additional_sources', sa.Text(), server_default='[]', nullable=False),
    sa.Column('gap_description', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=80), nullable=True),
    sa.Column('scanned_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.claim_id'], name=op.f('fk_evidence_findings_claim_id_claims')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], name=op.f('fk_evidence_findings_document_id_documents')),
    sa.ForeignKeyConstraint(['requirement_id'], ['code_evidence_requirements.requirement_id'], name=op.f('fk_evidence_findings_requirement_id_code_evidence_requirements')),
    sa.PrimaryKeyConstraint('finding_id', name=op.f('pk_evidence_findings'))
    )
    op.create_table('finding_dispositions',
    sa.Column('disposition_id', sa.String(length=36), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('original_amount', sa.Float(), nullable=False),
    sa.Column('adjusted_amount', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('decided_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('decided_at', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['opa_cases.case_id'], name=op.f('fk_finding_dispositions_case_id_opa_cases')),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['opa_users.user_id'], name=op.f('fk_finding_dispositions_decided_by_user_id_opa_users')),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.finding_id'], name=op.f('fk_finding_dispositions_finding_id_findings')),
    sa.PrimaryKeyConstraint('disposition_id', name=op.f('pk_finding_dispositions')),
    sa.UniqueConstraint('finding_id', name=op.f('uq_finding_dispositions_finding_id'))
    )
    with op.batch_alter_table('finding_dispositions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finding_dispositions_case_id'), ['case_id'], unique=False)

    op.create_table('prepay_finding_decisions',
    sa.Column('decision_id', sa.String(length=36), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('claim_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decided_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('decided_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.claim_id'], name=op.f('fk_prepay_finding_decisions_claim_id_claims')),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['opa_users.user_id'], name=op.f('fk_prepay_finding_decisions_decided_by_user_id_opa_users')),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.finding_id'], name=op.f('fk_prepay_finding_decisions_finding_id_findings')),
    sa.PrimaryKeyConstraint('decision_id', name=op.f('pk_prepay_finding_decisions')),
    sa.UniqueConstraint('finding_id', name=op.f('uq_prepay_finding_decisions_finding_id'))
    )
    with op.batch_alter_table('prepay_finding_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prepay_finding_decisions_claim_id'), ['claim_id'], unique=False)

    op.create_table('reconciliations',
    sa.Column('reconciliation_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('expected_amount', sa.Float(), nullable=False),
    sa.Column('actual_amount', sa.Float(), nullable=True),
    sa.Column('match_type', sa.String(length=30), nullable=False),
    sa.Column('recovery_835_transaction_id', sa.String(length=36), nullable=True),
    sa.Column('recovery_835_payment_id', sa.String(length=36), nullable=True),
    sa.Column('plb_reference', sa.String(length=100), nullable=True),
    sa.Column('treasury_reference', sa.String(length=100), nullable=True),
    sa.Column('exception_reason', sa.Text(), nullable=True),
    sa.Column('reconciled_at', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['opa_cases.case_id'], name=op.f('fk_reconciliations_case_id_opa_cases')),
    sa.ForeignKeyConstraint(['recovery_835_payment_id'], ['claim_payments_835.payment_id'], name=op.f('fk_reconciliations_recovery_835_payment_id_claim_payments_835')),
    sa.ForeignKeyConstraint(['recovery_835_transaction_id'], ['transactions_835.transaction_id'], name=op.f('fk_reconciliations_recovery_835_transaction_id_transactions_835')),
    sa.PrimaryKeyConstraint('reconciliation_id', name=op.f('pk_reconciliations'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reconciliations')
    with op.batch_alter_table('prepay_finding_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prepay_finding_decisions_claim_id'))

    op.drop_table('prepay_finding_decisions')
    with op.batch_alter_table('finding_dispositions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finding_dispositions_case_id'))

    op.drop_table('finding_dispositions')
    op.drop_table('evidence_findings')
    op.drop_table('era_adjustment_codes')
    op.drop_table('case_findings')
    op.drop_table('recoupment_actions')
    op.drop_table('provider_notices')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_recipient_unread')
        batch_op.drop_index('ix_notifications_recipient_created')

    op.drop_table('notifications')
    op.drop_table('likelihood_scores')
    op.drop_table('investigation_cases')
    op.drop_table('findings')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_claim_id'))
        batch_op.drop_index(batch_op.f('ix_documents_case_id'))

    op.drop_table('documents')
    op.drop_table('disputes')
    with op.batch_alter_table('contact_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_logs_case_id'))

    op.drop_table('contact_logs')
    op.drop_table('claim_payments_835')
    with op.batch_alter_table('case_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_notes_case_id'))

    op.drop_table('case_notes')
    op.drop_table('audit_logs')
    op.drop_table('siu_export_packages')
    op.drop_table('opa_cases')
    op.drop_table('law_enforcement_referrals')
    op.drop_table('investigation_notes')
    op.drop_table('connector_runs')
    op.drop_table('claim_lines')
    op.drop_table('user_roles')
    op.drop_table('siu_investigations')
    op.drop_table('runtime_config')
    op.drop_table('prioritization_config')
    op.drop_table('ml_training_config')
    op.drop_table('letter_templates')
    with op.batch_alter_table('document_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_templates_app'))

    op.drop_table('document_templates')
    op.drop_table('detector_rule_config')
    op.drop_table('connectors')
    op.drop_table('claims')
    op.drop_table('transactions_835')
    op.drop_table('role_apps')
    op.drop_table('providers')
    op.drop_table('opa_users')
    op.drop_table('fee_schedules')
    op.drop_table('cpt_modifier_map')
    op.drop_table('cpt_dx_coverage')
    op.drop_table('contract_limitations')
    op.drop_table('case_groups')
    with op.batch_alter_table('rule_prompts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_prompts_rule_id'))

    op.drop_table('rule_prompts')
    op.drop_table('roles')
    op.drop_table('revenue_codes')
    op.drop_table('reference_data_freshness')
    op.drop_table('provider_orgs')
    op.drop_table('modifier_codes')
    op.drop_table('ml_model_versions')
    op.drop_table('members')
    op.drop_table('icd_codes')
    with op.batch_alter_table('excluded_providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_excluded_providers_npi'))

    op.drop_table('excluded_providers')
    op.drop_table('evidence_requirements')
    op.drop_table('drg_codes')
    op.drop_table('cpt_coverage_gaps')
    op.drop_table('cpt_codes')
    op.drop_table('code_evidence_requirements')
    op.drop_table('bill_type_codes')
    op.drop_table('apps')
    # ### end Alembic commands ###
